export const kidsContent = {
  "5-8": {
    title: { en: "Money Adventures!", es: "¡Aventuras con Dinero!", ko: "돈의 모험!", zh: "金钱冒险！", ja: "お金の冒険！" },
    lessons: [
      { en: "When you trade your toy for a friend's toy, that's a TRANSACTION! The economy is just millions of trades like this.", es: "Cuando cambias tu juguete por el de un amigo, ¡eso es una TRANSACCIÓN!", ko: "장난감을 친구의 장난감과 교환하면, 그것이 거래입니다!", zh: "当你用玩具换朋友的玩具时，这就是交易！", ja: "おもちゃを友達のと交換したら、それが取引！" },
      { en: "If everyone wants the same toy but there aren't many, the price goes UP. That's like inflation!", es: "Si todos quieren el mismo juguete pero hay pocos, ¡el precio sube!", ko: "모두가 같은 장난감을 원하지만 적으면, 가격이 올라갑니다!", zh: "如果大家都想要同一个玩具但数量很少，价格就会上涨！", ja: "みんなが同じおもちゃを欲しがって数が少ないと値段が上がる！" },
      { en: "A piggy bank is like a little BANK. Money goes in (saving) and comes out (spending). The economy needs both!", es: "Una alcancía es como un BANCO pequeño. El dinero entra y sale.", ko: "돼지 저금통은 작은 은행과 같습니다. 돈이 들어가고(저축) 나옵니다(지출).", zh: "存钱罐就像一个小银行。钱进去（储蓄）又出来（消费）。", ja: "ブタの貯金箱は小さな銀行。お金が入って（貯蓄）出る（消費）。" },
      { en: "A NEED is something you must have, like food or a coat in winter. A WANT is something nice to have, like a new toy. Deciding which is which is a skill you'll use your whole life.", es: "Una NECESIDAD es algo que debes tener, como comida o un abrigo. Un DESEO es algo lindo de tener, como un juguete nuevo. ¡Saber la diferencia es una habilidad para toda la vida!", ko: "필요한 것은 음식이나 겨울 외투처럼 꼭 있어야 하는 것입니다. 원하는 것은 새 장난감처럼 있으면 좋은 것입니다. 둘을 구분하는 것은 평생 쓰는 기술이에요!", zh: "需要是你必须拥有的东西，比如食物或冬天的外套。想要是有了会很好的东西，比如新玩具。分清两者是你一辈子都会用到的本领！", ja: "「必要なもの」は食べ物や冬のコートのように絶対いるもの。「欲しいもの」は新しいおもちゃのようにあったら嬉しいもの。この区別は一生使うスキル！" },
      { en: "Doing a chore to earn your allowance is your very first PAYCHECK. Grown-ups earn money the same way — by doing work someone else values.", es: "Hacer una tarea para ganar tu mesada es tu primer SUELDO. ¡Los adultos ganan dinero de la misma forma!", ko: "심부름을 해서 용돈을 받는 것은 여러분의 첫 월급입니다. 어른들도 똑같이 다른 사람에게 가치 있는 일을 해서 돈을 법니다!", zh: "做家务赚零花钱就是你的第一份工资！大人赚钱的方式也是一样的——做别人认为有价值的工作。", ja: "お手伝いをしてお小遣いをもらうのが、あなたの初めての「お給料」！大人も同じように、誰かの役に立つ仕事をしてお金を稼ぐんだよ。" },
    ],
    activity: { en: "Set up a pretend store! Price items, buy and sell with play money. See how prices change when things are popular!", es: "¡Monta una tienda de juego! Pon precios, compra y vende.", ko: "놀이 가게를 열어보세요! 가격을 매기고, 놀이 돈으로 사고 팔아보세요.", zh: "开一个假装商店！给物品定价，用玩具钱买卖。", ja: "お店ごっこをしよう！値段をつけて、おもちゃのお金で売り買い。" },
    parentTip: { en: "Use allowance as a teaching tool: help them divide money into 'Spend,' 'Save,' and 'Give' jars.", es: "Usa la mesada como herramienta de enseñanza.", ko: "용돈을 교육 도구로 활용하세요: '쓰기', '저축', '나누기' 통으로 나누기.", zh: "用零花钱作为教学工具：分成'花费'、'储蓄'、'捐赠'三个罐子。", ja: "お小遣いを教育ツールに：「使う」「貯める」「あげる」の瓶に分けよう。" },
  },
  "9-12": {
    title: { en: "How Money Moves", es: "Cómo se Mueve el Dinero", ko: "돈의 움직임", zh: "钱如何流动", ja: "お金の動き" },
    lessons: [
      { en: "When your parents borrow money for a house (mortgage), they're using CREDIT. They pay it back over years with INTEREST — that's the cost of borrowing.", es: "Cuando tus padres piden un préstamo para una casa, usan CRÉDITO.", ko: "부모님이 집을 위해 돈을 빌리면 (모기지), 신용을 사용하는 것입니다.", zh: "父母借钱买房（按揭）就是在用信贷。他们多年还款加上利息。", ja: "親が家のためにお金を借りる（住宅ローン）時、それが信用。" },
      { en: "The economy goes through seasons like nature: Growth (spring) → Peak (summer) → Slowdown (fall) → Bottom (winter) → Growth again!", es: "La economía tiene estaciones como la naturaleza: Crecimiento → Pico → Desaceleración → Fondo → ¡Crecimiento otra vez!", ko: "경제도 자연처럼 계절이 있습니다: 성장(봄) → 정점(여름) → 둔화(가을) → 바닥(겨울) → 다시 성장!", zh: "经济像自然一样有四季：增长（春）→ 顶峰（夏）→ 放缓（秋）→ 低谷（冬）→ 再次增长！", ja: "経済にも自然のような季節がある：成長（春）→ ピーク（夏）→ 減速（秋）→ 底（冬）→ また成長！" },
      { en: "When your lemonade stand does well, you might borrow money to buy a bigger stand. If you earn more than the loan costs, that's GOOD debt!", es: "Si tu puesto de limonada va bien y pides prestado para uno más grande, ¡eso es deuda BUENA!", ko: "레모네이드 가판대가 잘 되면 더 큰 것을 사기 위해 빌릴 수 있습니다. 대출 비용보다 더 많이 벌면 좋은 부채입니다!", zh: "如果你的柠檬水摊生意好，借钱买更大的摊位，赚的比借的多，这就是好的债务！", ja: "レモネードスタンドが好調なら、大きな店を買うために借金。ローンより多く稼げば良い借金！" },
      { en: "Pick something you want that costs more than your allowance — a bike, a game console. Save a set amount every week and mark it on a chart. Watching the goal get closer is how real saving works.", es: "Elige algo que quieras que cueste más que tu mesada — una bici, una consola. Ahorra una cantidad fija cada semana y márcalo en un cuadro. ¡Así funciona el ahorro de verdad!", ko: "용돈보다 비싼 것(자전거, 게임기 등)을 정해보세요. 매주 정해진 금액을 저축하고 표에 표시하세요. 목표에 가까워지는 걸 지켜보는 것이 진짜 저축입니다.", zh: "挑一样你想要但比零花钱贵的东西——自行车、游戏机。每周存固定的钱并在图表上记录。看着目标一点点接近，这就是真正的储蓄。", ja: "お小遣いより高い欲しいもの（自転車やゲーム機）を選ぼう。毎週決まった額を貯めて表に記録。目標が近づくのを見るのが本当の貯蓄！" },
      { en: "A kids' savings account at a real bank lets you watch your own money add up on a statement, not just in a jar. It's the same account type — just smaller numbers — that adults use their whole lives.", es: "Una cuenta de ahorro infantil en un banco real te deja ver tu dinero crecer en un estado de cuenta, no solo en un frasco. ¡Es el mismo tipo de cuenta que usan los adultos toda su vida!", ko: "실제 은행의 어린이 저축 계좌를 만들면 저금통이 아니라 명세서에서 내 돈이 늘어나는 걸 볼 수 있어요. 어른들이 평생 쓰는 것과 같은 종류의 계좌예요, 숫자만 작을 뿐이죠.", zh: "在真正的银行开一个儿童储蓄账户，能让你在对账单上看到自己的钱增长，而不只是存钱罐。这和大人一辈子用的账户类型一样，只是数字更小。", ja: "本物の銀行の子ども用貯金口座なら、貯金箱じゃなく明細書で自分のお金が増えるのを見られる。大人が一生使うのと同じ種類の口座、数字が小さいだけ！" },
    ],
    activity: { en: "Track prices of 5 items at the grocery store for a month. Did they go up or down? You're measuring inflation!", es: "Rastrea precios de 5 artículos del super por un mes. ¡Estás midiendo la inflación!", ko: "한 달 동안 마트에서 5가지 품목의 가격을 추적해보세요. 인플레이션을 측정하고 있는 겁니다!", zh: "跟踪超市5件商品一个月的价格变化。你在测量通胀！", ja: "スーパーで5品目の価格を1ヶ月追跡。インフレを測定してるよ！" },
    parentTip: { en: "Open a savings account together. Show them interest earned — that's the bank paying to use their money!", es: "Abran una cuenta de ahorro juntos.", ko: "함께 저축 계좌를 개설하세요. 이자가 붙는 것을 보여주세요!", zh: "一起开个储蓄账户。让他们看到利息——银行付费使用他们的钱！", ja: "一緒に貯蓄口座を開こう。利息を見せて — 銀行がお金を借りた対価！" },
  },
  "13-17": {
    title: { en: "Real-World Economics", es: "Economía del Mundo Real", ko: "현실 세계의 경제학", zh: "现实世界经济学", ja: "実社会の経済学" },
    lessons: [
      { en: "Economists have a saying: every dollar you spend is someone else's income. When you buy a coffee, you pay the barista, who pays rent, whose landlord pays a mortgage. It's all connected!", es: "Los economistas tienen un dicho: cada dólar que gastas es el ingreso de alguien más. ¡Todo está conectado!", ko: "경제학자들이 흔히 하는 말이 있습니다: 당신이 쓰는 모든 달러는 다른 사람의 소득입니다. 커피를 사면 바리스타에게 돈이 가고, 그 사람이 월세를 내고, 집주인이 모기지를 갚습니다. 모두 연결되어 있습니다!", zh: "经济学家常说：你花的每一美元都是别人的收入。买咖啡时，你付钱给咖啡师，咖啡师付房租，房东付按揭。全都连在一起！", ja: "経済学者たちはこう言います：使った1ドルは誰かの収入になる。コーヒーを買えばバリスタに、バリスタは家賃を、大家はローンを。全部つながっている！" },
      { en: "The Fed is like a thermostat for the economy. Too hot (inflation)? Raise rates to cool it. Too cold (recession)? Lower rates to warm it up. But it takes 12-24 months to feel the change!", es: "El Fed es como un termostato económico. ¿Muy caliente? Sube tasas. ¿Muy frío? Baja tasas. ¡Tarda 12-24 meses en sentirse!", ko: "연준은 경제의 온도 조절 장치와 같습니다. 너무 뜨거우면(인플레이션)? 금리를 올려 식힙니다. 너무 차가우면(경기침체)? 금리를 내려 따뜻하게 합니다.", zh: "美联储就像经济的恒温器。太热（通胀）？加息降温。太冷（衰退）？降息升温。但需要12-24个月才能感受到变化！", ja: "FRBは経済のサーモスタット。熱すぎ（インフレ）？利上げで冷ます。寒すぎ（後退）？利下げで温める。でも効果は12-24ヶ月後！" },
      { en: "In 2008, banks lent too much to people who couldn't pay back. When the bubble burst, it created a deleveraging — the first in 75 years. The Fed printed $2+ trillion to stop the collapse.", es: "En 2008, los bancos prestaron demasiado a quienes no podían pagar. Cuando la burbuja estalló, el Fed imprimió $2T+.", ko: "2008년, 은행들이 갚을 수 없는 사람들에게 너무 많이 빌려줬습니다. 버블이 터지자 75년 만의 디레버리징이 발생했고, 연준은 $2조 이상을 발행했습니다.", zh: "2008年，银行向无力还款的人大量放贷。泡沫破裂时产生了75年来首次去杠杆。美联储印了2万亿+美元阻止崩溃。", ja: "2008年、銀行が返済できない人に貸しすぎた。バブル崩壊で75年ぶりのデレバレッジ。FRBは2兆ドル以上を印刷。" },
      { en: "A first job's paycheck, or a debit card loaded with allowance, works the same way: money leaves the account the moment you spend it. Checking the balance before you buy — not after — is the one habit that keeps a bank account out of trouble.", es: "El primer sueldo, o una tarjeta de débito con tu mesada, funciona igual: el dinero sale de la cuenta al gastar. Revisar el saldo ANTES de comprar es el hábito que evita problemas.", ko: "첫 아르바이트 월급이나 용돈이 들어있는 체크카드도 원리는 같습니다: 쓰는 순간 계좌에서 돈이 빠져나갑니다. 사기 전에 잔액을 확인하는 습관 하나가 계좌를 문제없이 지켜줍니다.", zh: "第一份工作的工资，或装有零花钱的借记卡，原理相同：一花钱账户里的钱就少了。花钱前先查余额——而不是花完再查——是让账户不出问题的唯一习惯。", ja: "初めてのバイト代や、お小遣いが入ったデビットカードも仕組みは同じ：使った瞬間に口座からお金が減る。買う前に残高を確認する習慣こそが、口座をトラブルから守る唯一の方法。" },
      { en: "\"Pay yourself first\" means putting a fixed slice of every dollar you earn into savings before you spend on anything else. Start that habit with your first paycheck and even a small percentage compounds into real money over decades.", es: "\"Págate a ti mismo primero\" significa apartar una parte fija de cada dólar que ganas en ahorro antes de gastar. ¡Empieza este hábito con tu primer sueldo!", ko: "\"나에게 먼저 지불하기\"란 번 돈 중 일정 비율을 다른 곳에 쓰기 전에 먼저 저축하는 것입니다. 첫 월급부터 이 습관을 시작하면 작은 비율도 수십 년에 걸쳐 큰돈이 됩니다.", zh: "\"先付钱给自己\"是指在花钱前，先把赚到的每一块钱中固定的一部分存起来。从第一份工资就开始这个习惯，哪怕比例很小，几十年后也会变成一笔可观的钱。", ja: "「自分に先払い」とは、稼いだお金の一定割合を、他に使う前にまず貯金すること。初めての給料からこの習慣を始めれば、小さな割合でも数十年でしっかりしたお金になる。" },
    ],
    activity: { en: "Pick a stock and track it for 3 months. Compare its movement to what the Fed does with rates. Can you see the connection?", es: "Elige una acción y síguala 3 meses. Compara con lo que hace el Fed.", ko: "주식 하나를 골라 3개월 동안 추적하세요. 연준의 금리 조치와 비교해보세요.", zh: "选一只股票追踪3个月。与美联储利率决策对比。能看到联系吗？", ja: "株を1つ選んで3ヶ月追跡。FRBの金利決定と比べてみよう。" },
    parentTip: { en: "Set up a practice investment account. Real-time experience is the best teacher for understanding market psychology.", es: "Configura una cuenta de inversión de práctica.", ko: "연습용 투자 계좌를 개설하세요. 실시간 경험이 시장 심리를 이해하는 최고의 교사입니다.", zh: "开设模拟投资账户。实时体验是理解市场心理的最佳老师。", ja: "練習用の投資口座を開設。リアルタイムの経験が市場心理を理解する最良の教師。" },
  },
};
