// SPLIT 2026-08-18 (owner-directed): lessons 1-15, the mechanics half of the old
// money track, now the optional `essentials` track. Content is byte-identical to
// what lessonContent.money.*.js held — the split moved entries, it did not edit them,
// which is why translation-review's englishSourceHash values are unchanged.
// ═══════════════════════════════════════════════════════════════════════════
// LESSON CONTENT — essentials track, English (en)
//
// One track, one language. Split this way 2026-08-17 (backlog item 45): the
// previous per-track files carried all five languages together, so
// lessonContent.money.js shipped 480 kB of body text to every reader while
// any one reader could read only their own ~97 kB of it. Four fifths of the
// largest asset in the app was text nobody on that device would ever see,
// and the chunk sat under Vite's 500 kB warning by less than a kilobyte.
//
// LessonReader.jsx dynamically import()s exactly one of these ten files —
// the open lesson's track, in the reader's active language.
//
// Fields are plain strings here, not { en, es, ... } maps. The language is
// the file. lessonContent.js re-assembles the language-map shape for the two
// node-only consumers that need every language at once (check-data.mjs's
// parity checks and translation-review.mjs's coverage hashes); nothing in
// the browser bundle imports that merged view.
//
// Generated mechanically from the pre-split files, byte-for-byte — see that
// commit for the equality proof. Edit this file directly from now on; it is
// source, not a build artifact, and there is no generator to re-run.
// ═══════════════════════════════════════════════════════════════════════════

export const lessonContent = {
  "1": {
    "sections": [
      {
        "heading": "Income vs. Expenses",
        "body": "Meet Maria, who just started her first job making $3,000 a month after taxes. A budget is simply her plan for that money: how much comes in (her paycheck) and how much goes out (rent, food, fun, savings).\n\nSome of Maria's expenses are fixed — her $1,200 rent and $50 phone bill show up at basically the same amount every month, whether she likes it or not. Others are variable — what she spends on groceries or going out with friends can swing a lot depending on the month.\n\nA simple starting split many people use: about 50% needs, 30% wants, 20% savings or debt payoff. For Maria's $3,000, that's roughly $1,500 for needs (rent, groceries, utilities), $900 for wants (eating out, hobbies, streaming), and $600 toward savings or paying down debt. That's a rule of thumb, not a rule — Maria's rent alone eats 40% of her pay, so she'll need to adjust the split to fit her real numbers, not force her numbers to fit the split."
      },
      {
        "heading": "Tracking Before Trimming",
        "body": "Before Maria cuts anything, it helps to simply track where her money already goes for one full month — every coffee, every subscription, no judgment yet, just data.\n\nYou can't manage what you don't measure. When Maria adds it up, she's surprised to find she's signed up for four different streaming services she barely watches — $12, $15, $9, and $18 a month. That's $54 a month, or $648 a year, quietly leaving her account for entertainment she'd mostly forgotten she was paying for.\n\nMost people find one or two categories like this, where spending drifted up without them really noticing — that's usually the easiest place to start trimming, not the hardest."
      },
      {
        "heading": "Make Saving Automatic, Not a Decision",
        "body": "Maria's budget puts $600 a month toward savings — but that only works if the $600 actually gets set aside, instead of quietly becoming part of whatever's left in her checking account by the end of the month. A budget that depends on remembering to save what's left over routinely fails, not because the plan was wrong, but because by the time rent, groceries, and a few unplanned purchases are done, there's rarely much left to remember.\n\nThe fix is to flip the order: set up an automatic transfer that moves $600 out of checking and into savings the same day her paycheck lands, before she's had a chance to spend any of it. The budget itself doesn't change — she's still following the same 50/30/20 split — but the savings portion no longer depends on Maria's discipline in week three of the month. It's already handled by week one.\n\nThis works for the same reason a habit is easier to keep than a fresh decision: it removes the moment where willpower is required. “Why 'Later' Never Feels as Real as 'Now'” (in Thinking About Money) covers why that moment is so easy to lose even for people who genuinely mean to save — the practical fix here is simply not to schedule that moment at all."
      }
    ],
    "takeaway": "A budget isn't about restriction — it's about knowing where your money goes so you can decide, on purpose, where it should go instead.",
    "thinkAbout": "Pick one week and write down every purchase, no matter how small. Most people are surprised by at least one category. What do you think yours will be?"
  },
  "2": {
    "sections": [
      {
        "heading": "What Counts as an Emergency",
        "body": "Imagine James's car breaks down on the way to work — a $600 repair he didn't see coming. Without savings set aside, that $600 goes straight onto a credit card, often at a high interest rate, turning one bad week into months of extra payments. An emergency fund is money set aside specifically for moments like this — a job loss, a medical bill, a car repair you can't skip. Not a sale, not a vacation.\n\nA common guideline is 3-6 months of essential expenses, though people with less predictable income (freelancers, commission-based jobs) sometimes aim higher.\n\nBuilding it doesn't have to happen all at once. If James starts by setting aside just $50 a week, he'd have covered that $600 repair within three months — and even a small starter fund, some suggest $500-1,000 to begin, already covers many common surprises like his."
      },
      {
        "heading": "Where to Keep It",
        "body": "The goal for emergency savings is safety and access, not growth. If James had put his emergency money into stocks instead, and the market happened to be down 15% the week his car broke down, he'd be forced to sell at a loss just to cover the repair. That's why the goal is a savings account he can reach within a day or two — not something tied up long-term (like a retirement account) or something that swings in value day to day (like stocks).\n\nThis is a different job than investing. An emergency fund's job is to be there when everything else in your life is not going according to plan, not to grow as fast as possible."
      },
      {
        "heading": "Emergency, or Just Irregular?",
        "body": "Not every surprise bill is really an emergency. A car repair from an accident is unpredictable. But car registration, holiday gifts, an annual insurance premium, or a friend's wedding are all expenses you could have seen coming — they just don't happen every month, so they feel like surprises when they land. Pulling from the emergency fund for these blurs the line and leaves less there for a genuine crisis.\n\nA separate tool handles this better: a sinking fund, where you set aside a little each month for a specific expense you know is coming (say, $50/month toward a $600 annual insurance bill), so the money is already there when the bill arrives. James's car repair — sudden, unplanned, unavoidable — is exactly what the emergency fund is for. His car registration renewal, due the same month every year, is not.\n\nAnd when the emergency fund is used, it isn't done — refilling it back to its target is the next month's priority, not an optional extra. A fund drawn down once and never rebuilt only protects you the first time."
      }
    ],
    "takeaway": "An emergency fund's whole purpose is to turn a crisis into an inconvenience.",
    "thinkAbout": "If your income stopped tomorrow, how many months could you cover your essential expenses with what you have saved right now?"
  },
  "3": {
    "sections": [
      {
        "heading": "Interest on Interest",
        "body": "Imagine you put $1,000 into an account earning 6% a year. With simple interest, you'd earn $60 every single year, forever, always calculated on that original $1,000. With compound interest, year one still earns $60 — but now your balance is $1,060, so year two's 6% is calculated on $1,060, earning $63.60. Year three is calculated on $1,123.60. The growth itself starts growing.\n\nIt looks small at first, but a rough shortcut called the Rule of 72 shows why it matters: divide 72 by an annual growth rate to estimate how many years it takes money to double. At 6% a year, that's about 12 years; at 9%, about 8 years. So that same $1,000 becomes roughly $2,000 in about 12 years, $4,000 in 24, and $8,000 in 36 — without adding another dollar. This is an approximation, not a precise formula, but it captures the idea well."
      },
      {
        "heading": "Time Beats Timing",
        "body": "Because compounding builds on itself, TIME matters enormously — often more than the amount you start with.\n\nSay Priya starts saving $200 a month at age 25, while her friend Tom waits until 35 and saves $400 a month — twice as much, every month — and both stop at 65. At the 6% from the example above they finish within about 1% of each other, near $400,000 apiece. Priya put in $96,000 of her own money along the way; Tom put in $144,000. Doubling the monthly amount is what it took to buy back a ten-year head start, and it only just did it — push the return a little higher and Priya ends up ahead, a little lower and Tom does.\n\nThe same math works against you with debt: interest you don't pay off compounds too, which is why carrying a credit card balance at a high interest rate for years can end up costing far more in interest than whatever you originally charged to the card."
      },
      {
        "heading": "Compounding Needs to Stay Invested",
        "body": "The math above only works if you leave the interest — or investment returns — in the account instead of pulling it out. If Priya's account pays 6% and she withdraws that 6% in cash every year to spend, she's back to simple interest: the same $60 a year, forever, on her original $1,000. The compounding disappears the moment growth isn't reinvested — the balance stops growing on top of itself and just sits there earning the same flat amount year after year.\n\nThis is why savings accounts, index funds, and dividend-paying stocks often have a \"reinvest\" setting — automatically buying more of the same investment with any interest or dividends earned, rather than paying it out as cash. Checking whether that setting is on (some accounts default to paying interest out instead of reinvesting it) is a five-minute task that can be the difference between watching a balance actually compound and watching it stay flat while every year's interest quietly disappears somewhere else. It's worth checking on every account you open, not just once — some providers reset the default when an account is renewed or transferred."
      }
    ],
    "takeaway": "Compounding rewards time above almost everything else — which makes today the earliest day you'll ever be able to start.",
    "thinkAbout": "Using the Rule of 72, roughly how many years would it take money to double at a 4% annual rate? At 12%?"
  },
  "4": {
    "sections": [
      {
        "heading": "What Goes Into a Score",
        "body": "Imagine two people, both with a $5,000 credit limit. Elena pays her balance in full every month and never carries more than $500 at a time — 10% of her available credit. David regularly carries a $4,000 balance — 80% of his limit — and has missed a couple of payments over the years. Even if both make the same income, Elena's credit score will typically be significantly higher, because a credit score is a number — in the US, commonly 300-850 — that summarizes how reliably you've repaid debt in the past, used by lenders to judge risk.\n\nThe biggest factors are usually payment history (do you pay on time, like Elena?) and credit utilization (how much of your available credit you're using, like David's 80%). Length of credit history, types of credit, and recent applications matter too, but less.\n\n“Productivity Growth” (in How the Economy Works) talked about good debt vs. bad debt for the economy; a credit score is asking a similar question about you personally: can you handle what you've borrowed?"
      },
      {
        "heading": "Why It Follows You",
        "body": "When Elena and David each apply for a $20,000 car loan, the bank might offer Elena 6% interest and David 14% for the exact same car — over a 5-year loan, that gap alone can add up to well over $2,000 in extra interest for David. A credit score can also affect whether an apartment will rent to you, and — depending on where you live — sometimes even job applications or insurance rates.\n\nBuilding a score like Elena's is mostly unglamorous: pay on time, every time; keep balances low relative to your limits; and let accounts age instead of closing them the moment they're paid off. There's no shortcut that replaces consistency over time."
      },
      {
        "heading": "Starting From Zero",
        "body": "But what if you don't have any credit history yet — no cards, no loans, nothing for a score to be calculated from? This is sometimes called the credit catch-22: many lenders want to see a track record before extending credit, but you can't build a track record without first getting some form of credit.\n\nA few common starting points exist for exactly this problem. A secured credit card requires a cash deposit — often $200-$500 — that becomes the card's credit limit, so the issuer's risk is covered by the deposit itself rather than by an existing credit history; used and paid off like a normal card, it reports to the bureaus the same way an unsecured card does. Being added as an authorized user on a trusted family member's older, well-managed card can also add that account's history to your own report. A credit-builder loan works almost backwards from an ordinary loan: the amount is held in a locked account while you make payments, and it's released to you only after the loan is fully repaid — the payments themselves are what build the history.\n\nWhichever starting point someone uses, the two factors from the first section — paying on time and keeping utilization low — still do almost all of the work from there."
      }
    ],
    "takeaway": "A credit score rewards boring, consistent behavior over years — there's no clever trick that substitutes for paying on time.",
    "thinkAbout": "Of the factors above, which one do you think would be easiest for you to improve first?"
  },
  "5": {
    "sections": [
      {
        "heading": "Two Basic Building Blocks",
        "body": "Imagine your favorite local coffee shop decides to expand into a national chain and sells small ownership slices to raise money — that's a stock. If you buy one, you now own a tiny sliver of that company. If the chain grows and becomes more valuable, your slice has historically tended to become more valuable too, though it can also lose value, including sharply, if the company struggles.\n\nA bond is closer to a loan: instead of buying a slice of the coffee chain, you lend it money directly, and it promises to pay you back with interest by a set date — like an IOU with predictable terms. Bonds have historically been less volatile than stocks, but they generally offer lower long-run average returns.\n\nNeither is inherently 'better' — a stock and a bond behave differently in the same conditions, which is exactly why people combine them."
      },
      {
        "heading": "Why Diversification Exists",
        "body": "Imagine putting your entire life savings into that one coffee chain's stock. If a competitor opens next door and steals half its customers, your entire savings takes the hit at once. Diversification means not putting all your money into one company, sector, or asset type — if one holding falls sharply, the rest can cushion the impact.\n\n“The 4 Phases of Economic Cycles” (in How the Economy Works) showed how different asset classes have historically performed differently across cycle phases — that pattern is part of why spreading investments across many holdings, rather than concentrating in a few (like that one coffee chain), has been a long-standing approach to managing risk.\n\nA fund that holds hundreds or thousands of companies at once — instead of just the one coffee chain — is one common way people diversify without picking individual stocks themselves."
      },
      {
        "heading": "What Diversification Doesn't Protect Against",
        "body": "Diversification cancels out one specific kind of risk: something that happens to a single company. If the coffee chain's new product flops, spreading your money across a thousand other companies means that one flop barely dents your total. This is called company-specific risk — it's diversifiable, because a hit to any one holding shrinks into a smaller share of a much bigger whole.\n\nBut there's a second kind of risk that diversifying within stocks alone can't touch: something that affects nearly the whole market at once. the four cycle phases in “The 4 Phases of Economic Cycles” showed that a broad economic contraction tends to pull most companies' stock prices down together, regardless of how many you hold — a thousand coffee chains, retailers, and tech firms all facing the same downturn don't cancel each other out the way one company's bad news does. This is often called market-wide, or systematic, risk, and it's the part that diversifying within a single asset class can't eliminate.\n\nThis is exactly why the previous section pointed at holding stocks *and* bonds, not just many different stocks. Bonds don't sidestep market-wide risk entirely, but they've historically tended to respond to the same conditions differently than stocks do — which is what actually cushions a portfolio during a downturn that no amount of stock-only diversification can."
      }
    ],
    "takeaway": "Stocks and bonds tend to respond differently to the same economic conditions — which is the whole point of holding both, not a coincidence.",
    "thinkAbout": "Think back to the four cycle phases in “The 4 Phases of Economic Cycles”. Why might holding both stocks and bonds smooth out the ride compared to holding just one?"
  },
  "6": {
    "sections": [
      {
        "heading": "Why These Accounts Exist",
        "body": "Picture two coworkers who each set aside $200 a month for 30 years and earn the same return on it. One puts the money in an ordinary brokerage account; the other puts it in a workplace 401(k). Every year, the brokerage saver owes tax on the dividends and interest their investments pay out, even though they never sold anything \u2014 and when they eventually do sell at a profit, that gain is taxed then too. The 401(k) saver owes nothing on that same growth until they actually withdraw it decades later — letting the full amount, tax included, keep compounding in the meantime (see “Compound Interest” on why compounding rewards time above almost everything else).\n\nA 401(k) is a retirement account offered through an employer; an IRA (Individual Retirement Account) is the equivalent that anyone can open on their own through a bank or brokerage, employer or not. Both exist for the same reason: the government designed them to encourage long-term saving by changing the tax treatment, not by changing what you're allowed to invest in — a 401(k) or IRA can hold many of the same stocks, bonds, or funds an ordinary brokerage account can.\n\nMany employers that offer a 401(k) also add a 'match' — contributing some additional money of their own whenever an employee contributes, up to a set limit. That match is usually subject to a vesting schedule (you may need to stay employed a certain number of years before it's fully yours), a detail worth checking rather than assuming."
      },
      {
        "heading": "Traditional vs Roth: Pay Tax Now or Later",
        "body": "Both the 401(k) and the IRA come in two versions that differ in exactly one place: when the tax bill comes due.\n\nA Traditional account is funded with money that hasn't been taxed yet — it lowers the saver's taxable income the year they contribute — but withdrawals in retirement are taxed as ordinary income. A Roth account works in reverse: it's funded with money that's already been taxed, so contributions don't reduce that year's taxable income, but qualified withdrawals in retirement are entirely tax-free, growth included.\n\nNeither version is universally better — it depends on a comparison nobody can make with certainty: is the saver's tax rate today higher or lower than it's likely to be decades from now, in retirement? A worker early in their career, likely earning less now than they will later, is often described as a candidate for Roth; a worker at peak career earnings, likely to have lower income in retirement, is often described as a candidate for Traditional. Both are simplifications of a genuinely individual, forward-looking tax question — not a rule that fits everyone, and not something this lesson can answer for any specific person."
      }
    ],
    "takeaway": "The account type doesn't change what you can invest in — it changes when the tax bill comes due. That single difference, compounded over decades, is why these accounts exist at all.",
    "thinkAbout": "“Compound Interest” showed that starting early matters more than starting big, because compounding needs time above all else. A tax-advantaged account doesn't add extra return by itself — it just lets more of the growth compound undisturbed. Why might that matter more the earlier someone starts?"
  },
  "7": {
    "sections": [
      {
        "heading": "Tax Brackets Are Layers, Not a Single Rate",
        "body": "Imagine income tax as a stack of buckets, each with its own rate, and money fills them from the bottom up. The first bucket might tax the first slice of income at a low rate; once that bucket is full, the next slice spills into a bucket taxed at a higher rate — but only that slice, not everything below it.\n\nThis is why a raise can never make your take-home pay go down, even if it pushes you into a new bracket. Say a worker's income grows enough to spill into a higher bucket. Only the new, additional slice of income — the part that overflowed into that higher bucket — gets taxed at the higher rate. Every dollar in the lower buckets keeps being taxed exactly as before.\n\nA common and costly misconception is thinking a raise, or a bonus, can leave you with less money overall by 'pushing you into a higher bracket.' It can't — it can only mean the marginal (extra) dollars are taxed a bit more, never that already-earned income gets taxed retroactively at the new, higher rate."
      },
      {
        "heading": "Gross Pay, Net Pay, and Where the Difference Goes",
        "body": "Look at any pay stub and two numbers stand out: gross pay (everything earned before anything is taken out) and net pay (what actually lands in the bank account). The gap between them is usually more than just income tax.\n\nIn the US, a paycheck typically also has separate payroll taxes withheld — funding programs like Social Security and Medicare — plus, depending on the state, a state income tax on top of the federal one. All of it is usually withheld automatically by the employer before the money ever reaches the worker, which is why most people never have to hand over a lump sum at tax time — most of it was already collected paycheck by paycheck.\n\nThis connects directly to “Retirement Accounts”: a Traditional 401(k) or IRA contribution is subtracted from income before it's taxed, which is exactly why it lowers the taxable income shown on that pay stub in the first place — not a separate mechanism, but this same withholding process working on a smaller number."
      },
      {
        "heading": "A Big Refund Isn't a Gift — It's an Interest-Free Loan",
        "body": "The withholding taken from every paycheck is only an estimate of the year's real tax bill, based on the answers given on a Form W-4 filled out when a job starts — filing status, number of jobs, other income. The real bill isn't calculated until a return is filed the following spring, months after most of the year's paychecks are already gone.\n\nIf the estimate withheld more than the real bill, the difference comes back as a refund. It was the worker's own money the whole time — handed over early, held with no interest, and returned later at the same face value. A $3,000 refund means $3,000 sat out of reach for months, unable to go toward a bill, a debt payment, or savings the moment it was earned.\n\nIf the estimate withheld less than the real bill, the worker owes the difference at filing, and a large enough gap can add an underpayment penalty. Neither outcome changes how much tax was owed for the year — the total is the same either way. Withholding only controls timing, not the size of the bill.\n\nThe W-4 is the lever for adjusting the estimate, and it's the document most workers fill out once, on their first day, and never revisit — even after a raise, a second job, a marriage, or a new dependent. A refund or amount owed that swings from year to year usually means an outdated W-4, not an unpredictable tax bill."
      }
    ],
    "takeaway": "Marginal tax brackets tax layers of income, not your whole income at one rate. A raise, a bonus, or extra freelance income can only ever add to your take-home pay, never subtract from it.",
    "thinkAbout": "Now that you understand how marginal brackets work, look back at the Traditional-vs-Roth question in “Retirement Accounts”. A Traditional contribution reduces taxable income at today's marginal rate. Does that change how you'd think about the 'higher tax rate now vs. later' comparison that lesson described?"
  },
  "8": {
    "sections": [
      {
        "heading": "Insurance Pools Risk Across Many People",
        "body": "Picture a neighborhood of a thousand homes. In any given year, maybe two or three will have a serious fire, but nobody knows in advance which ones. If each homeowner had to cover a fire's full cost alone, a handful of unlucky families would face a devastating loss while everyone else paid nothing.\n\nInsurance changes that math. Every homeowner pays a relatively small amount — the premium — into a shared pool. The insurer uses that pool to pay the full cost for the few homes that do have a fire that year. Nobody knows in advance whether they'll be one of the unlucky few, so everyone trades a small, certain cost (the premium) for protection against a large, uncertain one (rebuilding a house from nothing).\n\nThis is the same underlying idea across every type of insurance — health, auto, home or renters, life — just applied to a different kind of risk: a large group of people facing the same category of unpredictable loss, pooling small contributions so the few who actually experience it aren't left to cover it alone."
      },
      {
        "heading": "Premiums, Deductibles, and Coverage Limits",
        "body": "Three numbers shape almost every insurance policy. The premium is the recurring amount paid to keep the coverage active, whether or not a claim is ever filed. The deductible is the amount the policyholder pays out of pocket before the insurer starts paying anything on a claim. The coverage limit is the maximum the insurer will pay out, even if the actual loss is larger.\n\nThese three interact directly. A policy with a higher deductible generally carries a lower premium, because the policyholder is agreeing to absorb more of the smaller, more common losses themselves — the insurer only steps in once things get more expensive. A policy with a lower deductible generally carries a higher premium, since the insurer is taking on more of the cost from the very first dollar.\n\nThat trade-off — a bit more paid every month versus a bit more paid out of pocket if something goes wrong — depends on an individual's own finances, risk tolerance, and circumstances, not a rule this lesson can hand out. The goal here is understanding how the pieces fit together, not which combination is right for any specific person."
      },
      {
        "heading": "Adverse Selection and Moral Hazard: Why Insurers Ask So Many Questions",
        "body": "Section 1 explained that pooling only works because nobody knows in advance who the unlucky few will be. Two forces can quietly break that assumption, and insurers spend real effort managing both.\n\nThe first is adverse selection: people who already know they're higher-risk are more likely to buy insurance, and to buy more of it, than people who know they're low-risk — a smoker has more reason to want life insurance than a marathon runner does. If insurers charged everyone the same premium regardless, the pool would fill disproportionately with the people most likely to file, pushing premiums up for everyone. This is why applications ask about health history, driving records, or a home's condition before setting a price — sorting people into accurate risk groups is what keeps the pool viable at all.\n\nThe second is moral hazard: once a loss is covered, a policyholder's behavior can shift in ways that make a loss more likely, since they no longer bear its full cost. Deductibles exist partly for this reason — leaving the policyholder some skin in the game.\n\nSome losses fall outside what insurance can cover at all: something that's already happened, ordinary wear and tear rather than a sudden event, or damage entirely under the policyholder's own control. None involve the real uncertainty pooling depends on."
      }
    ],
    "takeaway": "Insurance doesn't eliminate risk — it pools it across many people so that a rare, large loss for one person becomes a small, predictable cost for everyone. Premiums, deductibles, and coverage limits are the three levers that shape that trade-off.",
    "thinkAbout": "“Emergency Funds” covered building an emergency fund for unexpected expenses. Insurance and an emergency fund solve related but different problems — one pools risk across many people for losses too large for most individual budgets, the other is money set aside by one person for smaller, more everyday surprises. Can you think of a loss each one would be better suited to cover?"
  },
  "9": {
    "sections": [
      {
        "heading": "Why a Dollar Buys Less Over Time",
        "body": "Ask a grandparent what a movie ticket or a loaf of bread cost when they were young, and the number will sound tiny. That's not because those things got more valuable — it's the flip side of the definition of inflation in “The Short-Term Debt Cycle” (in How the Economy Works): when spending and incomes across an economy grow faster than the goods and services actually produced, prices rise. Repeated year after year, that steady rise means the same dollar buys a little less each year than it did before.\n\nThis matters most for money that just sits still. Picture $1,000 in cash kept in a drawer for twenty years, never touched. The number printed on those bills never changes — it's still $1,000. But the groceries, gas, and rent that $1,000 could have covered on day one would cost noticeably more twenty years later, meaning that same stack of bills now covers less of ordinary life than it used to.\n\nThis isn't a flaw unique to cash in a drawer — it's what inflation does to purchasing power generally, whether the money is in a drawer, a low-interest savings account, or anywhere else that doesn't grow fast enough to keep up."
      },
      {
        "heading": "Real Return vs Nominal Return",
        "body": "A savings account that pays interest sounds like it's protecting against this problem — the balance grows every year, after all. But the number on the statement is the nominal return: growth measured in plain dollars, without asking what those dollars can actually buy.\n\nThe real return strips inflation back out: roughly, real return ≈ nominal return − inflation rate. If an account grows by a modest percentage in a year where prices across the economy rose by a similar or larger percentage, the balance is bigger in dollar terms but roughly flat — or even shrinking — in terms of what it can actually purchase. A bigger number on the screen doesn't automatically mean more real wealth.\n\nThis is exactly why the point about compounding in “Compound Interest” matters so much: compounding needs to outpace inflation, not just be positive, for an account's growth to translate into growing purchasing power rather than merely growing numbers."
      }
    ],
    "takeaway": "A growing account balance isn't the same as growing wealth. What matters is the real return — nominal growth minus inflation — because that's what determines whether your money's actual purchasing power is rising or falling.",
    "thinkAbout": "“Compound Interest” showed how compounding rewards time above almost everything else. Now add inflation to that picture: money that sits still, even in an account with a small positive interest rate, can still lose real purchasing power every year inflation outpaces it. Does that change how you think about the difference between saving and simply not spending?"
  },
  "10": {
    "sections": [
      {
        "heading": "Employee (W-2) or Independent Contractor (1099)?",
        "body": "A W-2 and a 1099 are both tax forms a worker receives each January summarizing the previous year's pay — but which one you get depends on your working relationship, not your job title. A W-2 means you're an employee: your employer directs how, when, and where the work gets done, and — as “Taxes” covered — automatically withholds income tax and payroll taxes from every paycheck. A 1099 means you were paid as an independent contractor: a business or client paid you for a service, but nothing was withheld, and no employer relationship existed.\n\nThe same kind of work can show up either way. A graphic designer on staff at an agency, with set hours and a manager, gets a W-2. A graphic designer who takes freelance projects for different clients, sets her own hours, and uses her own equipment gets a 1099 from each client who paid her over a threshold. The distinction isn't about what work was done — it's about who controls how it gets done, and it changes what happens with taxes."
      },
      {
        "heading": "The Self-Employment Tax: Paying Both Halves",
        "body": "“Taxes” explained that a paycheck's gap between gross and net includes payroll taxes funding Social Security and Medicare — and that an employer normally withholds and pays part of that automatically. What that lesson didn't say: the employer isn't paying that payroll tax alone. It's split roughly in half between employer and employee, with the employer's half never even appearing on the employee's pay stub.\n\nA 1099 contractor has no employer to cover that other half — so a self-employed person owes both halves themselves, a combined self-employment tax on top of ordinary income tax. Because nothing is automatically withheld from a 1099 payment the way it is from a W-2 paycheck, the responsibility shifts entirely onto the worker: setting money aside from every payment, and — depending on how much is owed — sending estimated tax payments to the IRS quarterly throughout the year rather than paying everything at once the following spring.\n\nThis is exactly why freelancers, gig workers, and small-business owners are consistently told to set aside roughly a quarter to a third of what they earn before it ever reaches their checking account: on a W-2, that setting-aside already happened automatically, paycheck by paycheck."
      }
    ],
    "takeaway": "The same work can arrive as a W-2 or a 1099, and that single distinction decides whether taxes are withheld automatically or become the worker's own responsibility to set aside and pay — including a self-employment tax that covers the half an employer would otherwise pay.",
    "thinkAbout": "“Taxes” showed that a raise can never shrink your take-home pay because payroll withholding just takes a slightly bigger automatic slice. Now picture that same raise arriving as 1099 income instead — with nothing withheld at all. Does thinking through what you'd need to set aside yourself change how you'd size up a freelance opportunity against a salaried one paying the same headline number?"
  },
  "11": {
    "sections": [
      {
        "heading": "The Expense Ratio: A Fee You Never Get a Bill For",
        "body": "Mutual funds and ETFs charge an annual fee called an expense ratio, expressed as a percentage of the money invested — for example, 0.05% or 1.00% per year. Unlike a phone bill or a subscription, nothing arrives in the mail asking to be paid: the fund simply deducts a small slice of the fund's total assets continuously, so the balance an investor sees has already had the fee taken out. That invisibility is exactly what makes it easy to ignore — there's no moment where the cost becomes obvious.\n\nExpense ratios vary enormously for reasons that have nothing to do with quality. A fund that simply tracks a market index (the diversification idea from “Stocks, Bonds & Diversification”, done automatically) needs little human decision-making to run, so index funds commonly charge 0.03%-0.20% a year. A fund where a manager actively picks investments, trying to beat the market, costs more to run and commonly charges 0.5%-1.5% a year — and that lesson's own point about diversification applies here too: most actively managed funds don't reliably beat a comparable index fund after fees, over long periods."
      },
      {
        "heading": "Why a Small Fee Becomes a Large One",
        "body": "“Compound Interest” showed that money grows fastest when compounding has the most years to work — and that the same math works against you with debt, where unpaid interest compounds too. A fee works exactly like that unpaid interest: it's subtracted every single year, including from the growth the fee took in prior years, so its cost compounds right alongside the investment's returns.\n\nSay $10,000 is invested for 30 years at a 7% annual return. In a fund charging 0.05%, fees are barely noticeable and the balance grows to roughly $75,000. In a fund charging 1.05% — a difference of exactly one percentage point — the effective annual growth rate drops to about 6%, and the balance reaches only around $57,000. That one-point difference, compounded over 30 years, consumed roughly a quarter of the total balance — not because the fee was charged once, but because it was charged every year on money that would otherwise have kept compounding.\n\nThis doesn't mean the cheapest fund is always the right choice, or that every fee is unjustified — some strategies genuinely cost more to run. But because a fee is guaranteed and compounds for as long as the money is invested, while a fund's future performance is not guaranteed, checking a fund's expense ratio before investing is one of the few things an investor can know for certain in advance."
      }
    ],
    "takeaway": "A fee never sends a bill, but it compounds every year exactly like the interest in “Compound Interest” — just working against the balance instead of for it, which is why even a fee under 1% is worth checking before investing.",
    "thinkAbout": "Two funds track the same market index and hold virtually identical investments, but one charges 0.05% and the other charges 0.75% a year. Since “Stocks, Bonds & Diversification” showed that diversification, not stock-picking skill, is what an index fund already provides, what would justify paying the higher fee for the same underlying holdings?"
  },
  "12": {
    "sections": [
      {
        "heading": "Renting vs. Buying: What Each Path Actually Costs",
        "body": "Rent and a mortgage payment look like the same kind of expense — a check written every month for housing — but they buy very different things. Rent buys the right to live somewhere for a fixed period, with no long-term claim on the property; when the lease ends, the renter walks away with nothing added to their own balance sheet. In exchange, a landlord absorbs the surprise costs of ownership — a broken water heater, a new roof, rising property taxes — and a renter can typically move with a month or two of notice.\n\nBuying trades that flexibility for something else: some of each mortgage payment builds equity, meaning a stake in the home the buyer keeps or gets back later. But buying also front-loads costs a renter never sees. A down payment plus closing costs — fees for the loan, title search, inspection, and more — commonly run 2%-5% of the purchase price, and selling later usually costs another 5%-6% in agent commissions — a rate that is negotiable rather than fixed. A homeowner is also on the hook for the exact surprise costs a landlord absorbed: property taxes, homeowner's insurance (the trade-a-small-cost-for-protection idea from “Insurance”, now mandatory for anyone with a mortgage), and repairs. None of this means buying is a mistake or renting is 'wasting money' — it means the two options bundle cost, risk, and flexibility differently, and which bundle fits depends on how long someone expects to stay and what they'd do with the money otherwise."
      },
      {
        "heading": "What a Mortgage Payment Is Actually Made Of",
        "body": "A mortgage is a loan that uses the home itself as collateral: if payments stop, the lender can foreclose and take the home to recover what's owed, which is why lenders can offer lower interest rates on a mortgage than on an unsecured loan like a credit card. A typical monthly payment bundles four things — principal (paying down the amount borrowed), interest (the lender's charge for the loan), property taxes, and homeowner's insurance — even though only the first two make up the loan itself.\n\nThe principal-and-interest split moves over the life of the loan in a pattern many buyers don't expect: early payments are mostly interest, and later payments are mostly principal. This is the same compounding math from “Compound Interest”, running against the borrower instead of for them — interest is charged on the full remaining balance, so when the balance is largest (right after buying), the interest portion is largest too. A 30-year loan often doesn't cross the halfway point between interest and principal until roughly two-thirds of the way through its term.\n\nA down payment below 20% of the purchase price usually adds one more cost: private mortgage insurance (PMI), which protects the lender — not the buyer — if the loan defaults, and typically cancels automatically once enough equity has built up. A larger down payment lowers the loan amount, the monthly payment, and often skips PMI entirely, which is part of why the size of a down payment is one of the most-discussed numbers in buying a home."
      }
    ],
    "takeaway": "Renting and buying aren't a 'right' and 'wrong' choice — they trade flexibility and predictable costs for equity and upfront risk in different amounts, and a mortgage payment itself splits into principal, interest, taxes, and insurance, with the interest share largest in the loan's early years.",
    "thinkAbout": "Someone is comparing an apartment renting for $1,800/month to a home where the mortgage, taxes, and insurance would total $1,900/month — almost the same. Given that buying also requires a down payment plus 2%-5% in closing costs upfront, and selling later costs another 5%-6% in commissions, what else would matter before concluding the two options cost 'about the same'?"
  },
  "13": {
    "sections": [
      {
        "heading": "What a Brokerage Account Is (and Isn't)",
        "body": "A brokerage account is just a container — a place to hold investments, not an investment itself. Opening one is normally free and doesn't commit any money on its own; the account only starts working once money is deposited and then used to buy something inside it, like the stocks, bonds, or funds “Stocks, Bonds & Diversification” covered.\n\nThat's easy to miss with cash sitting inside the account. Deposited money that hasn't been used to buy anything generally just sits there — a brokerage account isn't a savings account, so uninvested cash usually doesn't earn much, if anything, on its own. Buying an actual investment is a separate, deliberate step, not something that happens automatically just because money arrived.\n\nA taxable brokerage account is also a different animal from the 401(k) and IRA accounts “Retirement Accounts” covered. There's no contribution limit and no penalty for withdrawing money early, but gains are taxed as they're realized — when an investment is sold for a profit — rather than getting the tax-deferred or tax-free treatment a retirement account provides. Many people end up using both kinds of accounts for different goals: tax-advantaged accounts for retirement, and a taxable brokerage account for money that might be needed sooner."
      },
      {
        "heading": "Placing an Order: Market vs. Limit",
        "body": "Once money is in the account, buying or selling something requires placing an order, and the two most common types work differently. A market order says 'buy (or sell) right now, at whatever the best available price is' — it executes almost immediately, but the exact price isn't guaranteed down to the cent, especially if the price is moving fast. A limit order instead sets a specific price: 'only buy at this price or lower' (or 'only sell at this price or higher') — the price is guaranteed if the order executes, but there's no guarantee it executes at all, since the market might never reach that price.\n\nMost brokerages also let investors buy fractional shares — a slice of one share, like $50 worth of a stock trading at $500 — instead of requiring a purchase in whole-share amounts, which makes the diversification from “Stocks, Bonds & Diversification” easier to build with a smaller amount of money. And a completed trade doesn't finish instantly behind the scenes: shares typically 'settle' — officially change ownership — one business day after the trade, a detail that mostly only matters for quickly using the proceeds of a sale to buy something else."
      },
      {
        "heading": "If Trades Are Free, Who's Paying for This?",
        "body": "Most brokerages today don't charge a commission to buy or sell stocks — a real change from a few decades ago, when a single trade could cost $10-$30 no matter the size. But a company still needs revenue to operate, so \"free\" describes what the investor pays directly, not what the brokerage earns.\n\nThree revenue sources cover most of that gap. Interest: cash sitting in an account waiting to be invested — the same uninvested cash described above — is pooled across every customer and can be lent out or invested overnight by the brokerage itself, which keeps the interest, the same reason a bank can offer \"free\" checking. Payment for order flow: instead of sending every order straight to a public exchange, many brokerages route it to a market maker — a firm that fills the order directly and pays the brokerage a small fee for the right to do so. The bid-ask spread: at any moment a stock has a slightly higher price to buy (the ask) than to sell (the bid), often just a penny or two, and the market maker filling the order pockets that gap.\n\nNone of this is hidden or illegal — brokerages must publicly disclose their order-routing practices, and regulation requires trades to get \"best execution,\" a reasonable price given market conditions at that moment. But \"commission-free\" isn't the same as \"the brokerage has no stake in this trade.\" Worth remembering the next time something is advertised as free: it's worth asking, at least once, where the revenue is actually coming from."
      }
    ],
    "takeaway": "A brokerage account is a container, not an investment — opening one is free, but money inside it only grows once it's used to buy something. Market orders trade certainty of execution for uncertainty of price; limit orders do the opposite.",
    "thinkAbout": "Someone places a limit order to buy a stock 5% below its current price, hoping to get a better deal, but the price never drops that far and the order never executes. Compared to using a market order instead, what did they trade away — and what did they avoid risking?"
  },
  "14": {
    "sections": [
      {
        "heading": "A Will Isn't Just for the Wealthy",
        "body": "A will is a legal document that says who gets a person's belongings, money, and property after they die, and — for anyone with minor children — who would raise them. It's easy to assume a will only matters for someone with a large estate, but its real job is simpler: it lets a person's own wishes, not a default formula, decide what happens to what they leave behind.\n\nWithout a will, state law decides instead, through a process called intestate succession — a fixed formula (often splitting assets among a spouse and children in preset shares, or moving to more distant relatives if there's no immediate family) that applies the same way regardless of what the person would have actually wanted. It doesn't ask whether a couple was unmarried but together for decades, whether one child needed more support than another, or who the deceased would have actually chosen to raise their kids — it just follows the formula.\n\nA will doesn't have to be complicated to do its core job, and creating one is generally far less involved than most people assume — but the details (state-specific rules, notarization, witness requirements) are exactly the kind of thing that varies by location and situation, which is why this lesson explains what a will does rather than how to write one."
      },
      {
        "heading": "Beneficiary Designations Can Override a Will",
        "body": "Here's a detail that surprises a lot of people: a will doesn't control everything. Certain accounts — including the 401(k) and IRA accounts from “Retirement Accounts” and the life insurance policies from “Insurance” — pass directly to whoever is named as their beneficiary, regardless of what a will says. The account's own beneficiary designation wins, every time, even over a more recently written will that says something different.\n\nThis creates a specific, common, and entirely avoidable mistake: someone updates their will after a major life change — a divorce, a new child, a remarriage — but forgets that an old 401(k) or life insurance policy still lists an ex-spouse or an outdated beneficiary from years earlier. When that person dies, the account goes to whoever's name is on the beneficiary form, not whoever the will names or whoever the person would have actually wanted.\n\nThe practical takeaway isn't a specific instruction on what any one person's beneficiaries should be — that depends entirely on someone's own relationships and circumstances — but the mechanism itself: beneficiary forms are a separate, active decision from a will, and they don't update themselves just because life changed or a will was rewritten."
      }
    ],
    "takeaway": "A will directs how someone's belongings and money are distributed and who raises their children — without one, a fixed legal formula decides instead. But retirement and insurance accounts bypass a will entirely: whoever is named on the account's own beneficiary form gets it, so an outdated beneficiary designation can override even a brand-new will.",
    "thinkAbout": "Someone gets divorced, rewrites their will to leave everything to their new spouse, but never updates the beneficiary designation on the 401(k) they opened years earlier (“Retirement Accounts”) — it still lists their ex-spouse. Based on this lesson, who actually receives that 401(k) when they die?"
  },
  "15": {
    "sections": [
      {
        "heading": "The Report Is the Record; the Score Is a Number Calculated From It",
        "body": "A credit report is a detailed record of a person's borrowing history: which credit cards and loans they've opened, how much they owe, whether payments arrived on time or late, how long each account has existed, who has recently checked the report (a \"hard inquiry\"), and any public records like bankruptcies. It's compiled by a credit bureau — the three major ones in the U.S. are Equifax, Experian, and TransUnion — from information that lenders, landlords, and other creditors choose to report.\n\nA credit score is a different thing entirely: a three-digit number, typically ranging from 300 to 850, calculated from what's in a report using a scoring model such as FICO or VantageScore. The score isn't stored in the report — it's generated from the report's contents on demand, the way a GPA is calculated from a transcript rather than being written on it directly.\n\nBecause there are three bureaus and multiple scoring models, a single person doesn't have one credit score — they have several, and they can differ. Not every lender reports to all three bureaus, so Equifax's file on a person can be missing an account that shows up on Experian's, and FICO and VantageScore can each turn the same report into a slightly different number. Seeing two different scores in two different apps isn't a mistake — it can just mean the apps pulled from different bureaus or used different models."
      },
      {
        "heading": "Because a Report Is a Record, It Can Contain Errors — and Can Be Corrected",
        "body": "Because a credit report is compiled by a third party from other companies' data, it can be wrong in the ordinary ways any record compiled from multiple sources can be wrong: a payment that was on time gets logged as late, an account that was closed still shows as open, or — more seriously — information belonging to someone else with a similar name or a shared identity-theft situation ends up on the wrong file. Any of these can lower the score calculated from that report, for a reason that has nothing to do with the person's actual borrowing behavior.\n\nU.S. federal law entitles everyone to a free copy of their credit report from each of the three bureaus, available at AnnualCreditReport.com, and gives consumers the right to formally dispute inaccurate information directly with the bureau reporting it. This is a distinct action from improving a score: disputing a report fixes wrong information; it doesn't change accurate information into something more favorable.\n\nThat distinction matters because the two are often confused. If a report accurately shows a history of late payments or a high amount owed relative to available credit, disputing it won't remove that information — a score calculated from accurate information changes only as the underlying behavior does, over time. Checking a report for errors and improving the habits it accurately reflects are two different, both worthwhile, things to do."
      }
    ],
    "takeaway": "A credit report is a detailed record of someone's borrowing history, kept separately by three different bureaus (Equifax, Experian, TransUnion). A credit score is a three-digit number calculated from that report by a scoring model (like FICO or VantageScore) — since there are three bureaus and multiple models, one person has several scores, not one. Because a report is compiled from other companies' data, it can contain errors; U.S. law entitles everyone to a free copy from each bureau and the right to dispute inaccuracies, but disputing only fixes wrong information — it doesn't change what's accurately reported.",
    "thinkAbout": "Someone checks their credit score on their bank's app and sees 705, then checks a different free app the same day and sees 680. Based on this lesson, what's the most likely explanation — and is one of the two numbers necessarily wrong?"
  },
};
