// SPLIT 2026-08-18 (owner-directed): lessons 1-15, the mechanics half of the old
// money track, now the optional `essentials` track. Content is byte-identical to
// what lessonContent.money.*.js held — the split moved entries, it did not edit them,
// which is why translation-review's englishSourceHash values are unchanged.
// ═══════════════════════════════════════════════════════════════════════════
// LESSON CONTENT — essentials track, Spanish (es)
//
// One track, one language. Split this way 2026-08-17 (backlog item 45): the
// previous per-track files carried all five languages together, so
// lessonContent.money.js shipped 480 kB of body text to every reader while
// any one reader could read only their own ~97 kB of it. Four fifths of the
// largest asset in the app was text nobody on that device would ever see,
// and the chunk sat under Vite's 500 kB warning by less than a kilobyte.
//
// LessonReader.jsx dynamically import()s exactly one of these ten files —
// the open lesson's track, in the reader's active language.
//
// Fields are plain strings here, not { en, es, ... } maps. The language is
// the file. lessonContent.js re-assembles the language-map shape for the two
// node-only consumers that need every language at once (check-data.mjs's
// parity checks and translation-review.mjs's coverage hashes); nothing in
// the browser bundle imports that merged view.
//
// Generated mechanically from the pre-split files, byte-for-byte — see that
// commit for the equality proof. Edit this file directly from now on; it is
// source, not a build artifact, and there is no generator to re-run.
// ═══════════════════════════════════════════════════════════════════════════

export const lessonContent = {
  "1": {
    "sections": [
      {
        "heading": "Ingresos vs. Gastos",
        "body": "María acaba de empezar su primer trabajo y gana $3,000 al mes después de impuestos. Un presupuesto es simplemente su plan para ese dinero: cuánto entra (su sueldo) y cuánto sale (alquiler, comida, ocio, ahorro).\n\nAlgunos gastos de María son fijos — su alquiler de $1,200 y su factura de teléfono de $50 llegan prácticamente por el mismo importe cada mes, le guste o no. Otros son variables — lo que gasta en la compra o en salir con amigos puede oscilar bastante según el mes.\n\nUna división simple que mucha gente usa para empezar: alrededor de 50% necesidades, 30% deseos, 20% ahorro o pago de deudas. Para los $3,000 de María, eso son unos $1,500 para necesidades (alquiler, compra, servicios), $900 para deseos (comer fuera, aficiones, streaming) y $600 para ahorrar o reducir deuda. Es una guía, no una regla — el alquiler de María se lleva él solo el 40% de su sueldo, así que tendrá que ajustar la división a sus números reales, en vez de forzar sus números para que encajen en la división."
      },
      {
        "heading": "Registrar Antes de Recortar",
        "body": "Antes de que María recorte nada, ayuda simplemente registrar durante un mes entero a dónde va ya su dinero — cada café, cada suscripción, sin juzgar todavía, solo datos.\n\nNo puedes gestionar lo que no mides. Al sumarlo, María descubre con sorpresa que está suscrita a cuatro servicios de streaming distintos que apenas ve — $12, $15, $9 y $18 al mes. Son $54 al mes, o $648 al año, saliendo en silencio de su cuenta por un entretenimiento que casi había olvidado que estaba pagando.\n\nLa mayoría de la gente encuentra una o dos categorías así, donde el gasto fue subiendo sin que se dieran cuenta de verdad — y ese suele ser el sitio más fácil por donde empezar a recortar, no el más difícil."
      },
      {
        "heading": "Automatiza el Ahorro, No Lo Decidas",
        "body": "El presupuesto de María destina $600 al mes al ahorro — pero eso solo funciona si los $600 se apartan de verdad, en vez de quedar disueltos en lo que sobre en su cuenta corriente a fin de mes. Un presupuesto que depende de acordarse de ahorrar lo que sobra falla una y otra vez, no porque el plan estuviera mal, sino porque para cuando están pagados el alquiler, la compra y algún gasto imprevisto, rara vez sobra mucho de lo que acordarse.\n\nLa solución es invertir el orden: programar una transferencia automática que saque $600 de la cuenta corriente y los lleve a ahorros el mismo día que llega el sueldo, antes de que María haya tenido ocasión de gastar nada. El presupuesto en sí no cambia — sigue con la misma división 50/30/20 — pero la parte de ahorro ya no depende de la disciplina de María en la tercera semana del mes. Ya está resuelta en la primera.\n\nEsto funciona por la misma razón por la que un hábito es más fácil de mantener que una decisión nueva: elimina el momento en que hace falta fuerza de voluntad. “Por Qué 'Luego' Nunca Se Siente Tan Real Como 'Ahora'” (en Pensar sobre el dinero) explica por qué ese momento se pierde con tanta facilidad incluso en quienes de verdad piensan ahorrar — y la solución práctica aquí es sencillamente no programar ese momento."
      }
    ],
    "takeaway": "Un presupuesto no es restricción — es saber a dónde va tu dinero para poder decidir, a propósito, a dónde debería ir.",
    "thinkAbout": "Elige una semana y anota cada compra, sin importar cuán pequeña. La mayoría se sorprende de al menos una categoría. ¿Cuál crees que será la tuya?"
  },
  "2": {
    "sections": [
      {
        "heading": "Qué Cuenta Como Emergencia",
        "body": "Imagina que el auto de James se avería camino al trabajo — una reparación de $600 que no vio venir. Sin ahorros reservados, esos $600 van directo a una tarjeta de crédito, a menudo con una tasa de interés alta, convirtiendo una mala semana en meses de pagos extra. Un fondo de emergencia es dinero reservado específicamente para momentos así — perder el empleo, una factura médica, una reparación del auto que no puedes postergar. No una oferta, no unas vacaciones.\n\nUna guía común es 3-6 meses de gastos esenciales, aunque las personas con ingresos menos predecibles (freelancers, trabajos por comisión) a veces apuntan más alto.\n\nConstruirlo no tiene que lograrse de golpe. Si James empieza reservando solo $50 a la semana, habría cubierto esa reparación de $600 dentro de tres meses — e incluso un pequeño fondo inicial, algunos sugieren $500-1,000 para empezar, ya cubre muchas sorpresas comunes como la suya."
      },
      {
        "heading": "Dónde Guardarlo",
        "body": "El objetivo del ahorro de emergencia es seguridad y acceso, no crecimiento. Si James hubiera puesto su dinero de emergencia en acciones y el mercado hubiera estado 15% abajo la semana que se le averió el auto, se habría visto forzado a vender con pérdida solo para cubrir la reparación. Por eso el objetivo es una cuenta de ahorros a la que pueda acceder en un día o dos — no algo bloqueado a largo plazo (como una cuenta de jubilación) ni algo que fluctúa de valor día a día (como las acciones).\n\nEs un trabajo distinto al de invertir. El trabajo de un fondo de emergencia es estar ahí cuando todo lo demás en tu vida no va según el plan, no crecer lo más rápido posible."
      },
      {
        "heading": "¿Emergencia, o Simplemente Irregular?",
        "body": "No toda factura sorpresa es realmente una emergencia. La reparación de un auto por un accidente es impredecible. Pero la renovación de la placa, los regalos navideños, una prima de seguro anual o la boda de un amigo son todos gastos que podrías haber visto venir — simplemente no ocurren cada mes, así que se sienten como sorpresas cuando llegan. Sacar del fondo de emergencia para estos casos borra la línea y deja menos disponible para una crisis genuina.\n\nUna herramienta aparte maneja esto mejor: un fondo de reserva (sinking fund), donde apartas un poco cada mes para un gasto específico que sabes que viene (digamos, $50 al mes para una factura de seguro anual de $600), así el dinero ya está ahí cuando llega la factura. La reparación del auto de James — súbita, no planificada, inevitable — es exactamente para lo que sirve el fondo de emergencia. La renovación de la placa de su auto, que vence el mismo mes cada año, no lo es.\n\nY cuando el fondo de emergencia se usa, no está terminado — rellenarlo hasta su objetivo es la prioridad del mes siguiente, no un extra opcional. Un fondo que se agota una vez y nunca se reconstruye solo te protege la primera vez."
      }
    ],
    "takeaway": "El propósito del fondo de emergencia es convertir una crisis en una molestia.",
    "thinkAbout": "Si tu ingreso se detuviera mañana, ¿cuántos meses podrías cubrir tus gastos esenciales con lo que tienes ahorrado?"
  },
  "3": {
    "sections": [
      {
        "heading": "Interés Sobre Interés",
        "body": "Imagina que pones $1,000 en una cuenta que rinde 6% al año. Con interés simple, ganarías $60 cada año, para siempre, siempre calculado sobre esos $1,000 originales. Con interés compuesto, el primer año también gana $60 — pero ahora tu saldo es $1,060, así que el 6% del segundo año se calcula sobre $1,060 y gana $63.60. El tercer año se calcula sobre $1,123.60. El crecimiento mismo empieza a crecer.\n\nAl principio parece poco, pero un atajo aproximado llamado Regla del 72 muestra por qué importa: divide 72 entre la tasa de crecimiento anual para estimar en cuántos años se duplica el dinero. Al 6% al año son unos 12 años; al 9%, unos 8. Así que esos mismos $1,000 se convierten en unos $2,000 en unos 12 años, $4,000 en 24 y $8,000 en 36 — sin añadir un dólar más. Es una aproximación, no una fórmula exacta, pero capta bien la idea."
      },
      {
        "heading": "El Tiempo Vence a la Sincronización",
        "body": "Porque el interés compuesto se construye sobre sí mismo, el TIEMPO importa enormemente — a menudo más que el monto inicial.\n\nDigamos que Priya empieza a ahorrar $200 al mes a los 25 años, mientras que su amigo Tom espera hasta los 35 y ahorra $400 al mes — el doble, cada mes — y ambos paran a los 65. Con el 6% del ejemplo anterior terminan a un 1% aproximadamente el uno del otro, cerca de $400,000 cada uno. Priya puso $96,000 de su propio dinero por el camino; Tom puso $144,000. Duplicar la cuota mensual fue lo que hizo falta para recuperar una ventaja de diez años, y apenas alcanzó — sube un poco el rendimiento y Priya termina por delante; bájalo un poco y termina Tom.\n\nLa misma matemática funciona en tu contra con las deudas: el interés que no pagas también se compone, y por eso arrastrar durante años el saldo de una tarjeta de crédito con una tasa alta puede acabar costando mucho más en intereses que lo que cargaste originalmente a la tarjeta."
      },
      {
        "heading": "El Interés Debe Reinvertirse",
        "body": "La matemática anterior solo funciona si dejas el interés — o los rendimientos de inversión — en la cuenta en vez de retirarlo. Vuelve a esos primeros $1,000 al 6%: si retiras los $60 en efectivo cada año para gastarlos, vuelves al interés simple — los mismos $60 al año, para siempre, sobre los $1,000 originales. El interés compuesto desaparece en el momento en que el crecimiento no se reinvierte — el saldo deja de crecer sobre sí mismo y se queda ahí, ganando la misma cantidad fija año tras año.\n\nPor eso las cuentas de ahorro, los fondos indexados y las acciones que pagan dividendos suelen tener una opción de \"reinvertir\" — comprar automáticamente más de la misma inversión con el interés o los dividendos ganados, en vez de pagarlos en efectivo. Revisar si esa opción está activada (algunas cuentas vienen configuradas para pagar el interés en vez de reinvertirlo) es una tarea de cinco minutos que puede ser la diferencia entre ver un saldo componerse de verdad y verlo estancado mientras el interés de cada año desaparece discretamente en otra parte. Vale la pena revisarlo en cada cuenta que abras, y no una sola vez — algunos proveedores restablecen la configuración por defecto cuando una cuenta se renueva o se transfiere."
      }
    ],
    "takeaway": "El interés compuesto premia el tiempo por encima de casi todo — lo que hace que hoy sea el día más temprano que tendrás para empezar.",
    "thinkAbout": "Usando la Regla del 72, ¿aproximadamente cuántos años tardaría el dinero en duplicarse a una tasa anual del 4%? ¿Y al 12%?"
  },
  "4": {
    "sections": [
      {
        "heading": "Qué Compone el Puntaje",
        "body": "El puntaje de crédito es un número — en EE.UU. suele ir de 300 a 850 — que resume qué tan confiablemente has pagado tus deudas, usado por prestamistas para evaluar el riesgo.\n\nLos factores más grandes suelen ser el historial de pagos y el uso del crédito disponible. La duración del historial, los tipos de crédito y las solicitudes recientes también importan, pero menos.\n\n“Crecimiento de Productividad” (en Cómo funciona la economía) habló de la deuda buena frente a la mala para la economía; un puntaje de crédito hace una pregunta parecida sobre ti: ¿puedes con lo que has pedido prestado?"
      },
      {
        "heading": "Por Qué Te Acompaña",
        "body": "El puntaje de crédito puede afectar la tasa de interés en un préstamo para auto o hipoteca, si un apartamento te alquilará, y a veces incluso solicitudes de empleo o tarifas de seguro.\n\nConstruirlo es poco glamuroso: paga a tiempo siempre; mantén saldos bajos; deja que las cuentas envejezcan en vez de cerrarlas."
      },
      {
        "heading": "Empezar Desde Cero",
        "body": "¿Qué pasa si no tienes historial crediticio — ni tarjetas, ni préstamos, nada de donde calcular un puntaje? Es el llamado catch-22 del crédito: los prestamistas quieren ver un historial antes de dar crédito, pero no puedes construir un historial sin antes obtener algún tipo de crédito.\n\nExisten puntos de partida comunes: una tarjeta de crédito garantizada requiere un depósito en efectivo (a menudo $200-$500) que se convierte en el límite de la tarjeta, cubriendo el riesgo del emisor con el depósito mismo; usada y pagada como una tarjeta normal, reporta a las agencias igual que una tarjeta sin garantía. Ser agregado como usuario autorizado en una tarjeta antigua y bien manejada de un familiar de confianza también puede sumar ese historial al tuyo propio. Un préstamo para construir crédito funciona casi al revés de un préstamo normal: el monto se guarda en una cuenta bloqueada mientras haces los pagos, y se te entrega solo después de pagarlo por completo — los pagos mismos son los que construyen el historial.\n\nCualquiera sea el punto de partida, los dos factores de la primera sección — pagar a tiempo y mantener bajo el uso del crédito — siguen haciendo casi todo el trabajo desde ahí."
      }
    ],
    "takeaway": "El puntaje de crédito premia el comportamiento aburrido y constante durante años — no hay truco que sustituya pagar a tiempo.",
    "thinkAbout": "De los factores anteriores, ¿cuál crees que sería el más fácil de mejorar primero?"
  },
  "5": {
    "sections": [
      {
        "heading": "Dos Bloques Básicos",
        "body": "Imagina que tu cafetería local favorita decide expandirse y convertirse en una cadena nacional, y vende pequeñas porciones de propiedad para reunir dinero — eso es una acción. Si compras una, pasas a ser dueño de una porción diminuta de esa empresa. Si la cadena crece y vale más, tu porción históricamente ha tendido a valer más también, aunque también puede perder valor, incluso de forma brusca, si la empresa tiene problemas.\n\nUn bono se parece más a un préstamo: en vez de comprar una porción de la cadena de café, le prestas dinero directamente, y ella promete devolvértelo con interés en una fecha fijada — como un pagaré de condiciones previsibles. Los bonos han sido históricamente menos volátiles que las acciones, pero suelen ofrecer retornos promedio más bajos a largo plazo.\n\nNinguno de los dos es intrínsecamente «mejor» — una acción y un bono a menudo se comportan de forma distinta en las mismas condiciones, y por eso la gente los combina."
      },
      {
        "heading": "Por Qué Existe la Diversificación",
        "body": "Imagina poner todos los ahorros de tu vida en la acción de esa única cadena de café. Si un competidor abre al lado y se lleva la mitad de sus clientes, todos tus ahorros reciben el golpe de una vez. Diversificar significa no poner todo el dinero en una empresa, sector o tipo de activo. Si una inversión cae bruscamente, el resto puede amortiguar el impacto.\n\nLa lección “Las 4 Fases del Ciclo Económico” (en Cómo funciona la economía) mostró cómo distintas clases de activos se han comportado diferente según la fase del ciclo — ese patrón es parte de por qué repartir inversiones en muchas posiciones, en vez de concentrarse en pocas (como esa única cadena de café), ha sido un enfoque duradero para gestionar el riesgo.\n\nUn fondo que tiene cientos o miles de empresas a la vez — en lugar de solo la cadena de café — es una forma común de diversificar sin elegir acciones individuales uno mismo."
      },
      {
        "heading": "Lo Que la Diversificación No Puede Evitar",
        "body": "La diversificación elimina un tipo específico de riesgo: algo que le pasa a una sola empresa. Si el nuevo producto de la cadena de café fracasa, repartir tu dinero entre miles de otras empresas hace que ese fracaso apenas te afecte — esto se llama riesgo específico de la empresa, y es diversificable, porque el golpe a cualquier posición se encoge hasta ser una porción pequeña de un conjunto mucho mayor.\n\nPero hay un segundo tipo de riesgo que la diversificación dentro de las acciones no puede eliminar: algo que afecta a casi todo el mercado a la vez. Las cuatro fases de la lección “Las 4 Fases del Ciclo Económico” (en Cómo funciona la economía) mostraron que una contracción económica amplia tiende a arrastrar hacia abajo el precio de la mayoría de las acciones juntas, sin importar cuántas empresas tengas — mil cadenas de café, minoristas y empresas tecnológicas que enfrentan la misma recesión no se cancelan entre sí como sí lo hace la mala noticia de una sola empresa. Esto se llama riesgo sistemático (o de mercado), y es la parte que diversificar dentro de una sola clase de activos no puede eliminar.\n\nPor eso la sección anterior señalaba tener acciones y bonos, no solo muchas acciones distintas. Los bonos no evitan el riesgo de mercado por completo, pero a menudo responden de forma diferente a las mismas condiciones — y cuando lo hacen, esa diferencia amortigua una caída como ninguna diversificación solo en acciones puede lograr.\n\nPero es una tendencia, no una regla, y va y viene. Medidos mes a mes, en Estados Unidos las acciones y los bonos se movieron juntos durante los años setenta, ochenta y noventa, en sentido opuesto desde finales de los noventa hasta 2021, y juntos otra vez en los años posteriores a 2022. En 2008 la amortiguación funcionó tal como se describe: las acciones cayeron cerca de un 37% mientras un fondo amplio de bonos estadounidenses rendía cerca de un 8%. En 2022 no estuvo ahí: el mismo año, las acciones cayeron cerca de un 18% y ese mismo tipo de fondo de bonos cayó cerca de un 13%."
      }
    ],
    "takeaway": "Las acciones y los bonos suelen responder distinto a las mismas condiciones económicas — ese es el punto de tener ambos. Pero «suelen» no es «siempre»: en 2022 cayeron juntos.",
    "thinkAbout": "Piensa en las cuatro fases del ciclo de la lección “Las 4 Fases del Ciclo Económico” (en Cómo funciona la economía). ¿Por qué tener acciones y bonos juntos podría suavizar el camino comparado con tener solo uno?"
  },
  "6": {
    "sections": [
      {
        "heading": "Por Qué Existen Estas Cuentas",
        "body": "Imagina a dos compañeros de trabajo que apartan $200 al mes durante 30 años y obtienen el mismo rendimiento. Uno pone el dinero en una cuenta de corretaje ordinaria; el otro lo pone en un 401(k) de su empresa. Cada año, quien ahorra en la cuenta de corretaje paga impuestos sobre los dividendos y los intereses que reparten sus inversiones, aunque no haya vendido nada — y cuando finalmente venda con ganancia, esa ganancia también se grava entonces. Quien ahorra en el 401(k) no debe nada por ese mismo crecimiento hasta que retire el dinero décadas después, lo que deja que el importe completo, impuestos incluidos, siga capitalizándose mientras tanto (véase “Interés Compuesto” sobre por qué la capitalización premia al tiempo por encima de casi todo lo demás).\n\nUn 401(k) es una cuenta de jubilación ofrecida a través de un empleador; un IRA (Individual Retirement Account, cuenta de jubilación individual) es el equivalente que cualquiera puede abrir por su cuenta en un banco o una casa de bolsa, tenga empleador o no. Ambos existen por la misma razón: el gobierno los diseñó para fomentar el ahorro a largo plazo cambiando el tratamiento fiscal, no cambiando en qué se permite invertir — un 401(k) o un IRA puede contener muchas de las mismas acciones, bonos o fondos que una cuenta de corretaje ordinaria.\n\nMuchos empleadores que ofrecen un 401(k) añaden además un 'match' — aportan algo de dinero propio cada vez que el empleado contribuye, hasta un límite establecido. Ese match suele estar sujeto a un período de adquisición de derechos (puede que necesites seguir empleado cierto número de años antes de que sea plenamente tuyo), un detalle que conviene comprobar en lugar de darlo por supuesto."
      },
      {
        "heading": "Traditional vs Roth: Pagar Impuestos Ahora o Después",
        "body": "Tanto el 401(k) como el IRA existen en dos versiones, y la mayor diferencia entre ellas es cuándo llega la factura fiscal.\n\nUna cuenta Traditional se financia con dinero que todavía no ha sido gravado — normalmente reduce el ingreso gravable del año en que se contribuye — pero los retiros en la jubilación se gravan como ingreso ordinario. Una cuenta Roth funciona al revés: se financia con dinero que ya fue gravado, así que las contribuciones no reducen el ingreso gravable de ese año, pero los retiros calificados en la jubilación están completamente libres de impuestos, crecimiento incluido. También difieren reglas menores, como los límites de ingreso para contribuir a un Roth IRA y los retiros obligatorios de las cuentas Traditional.\n\nNinguna versión es mejor de forma universal — depende de una comparación que nadie puede hacer con certeza: ¿la tasa de impuestos de quien ahorra es hoy más alta o más baja de lo que probablemente será dentro de décadas, ya jubilado? De un trabajador al principio de su carrera, que probablemente gana ahora menos de lo que ganará después, suele decirse que es candidato a Roth; de un trabajador en el pico de sus ingresos, que probablemente tendrá menos ingresos en la jubilación, suele decirse que es candidato a Traditional. Ambas son simplificaciones de una cuestión fiscal genuinamente individual y orientada al futuro — no una regla que le sirva a todo el mundo, y no algo que esta lección pueda responder para ninguna persona en concreto."
      }
    ],
    "takeaway": "El tipo de cuenta no cambia en qué puedes invertir — cambia cuándo llega el impuesto. Esa diferencia, compuesta durante décadas, es la razón de ser de estas cuentas.",
    "thinkAbout": "La lección “Interés Compuesto” mostró que empezar temprano importa más que empezar en grande, porque la capitalización necesita tiempo sobre todo. Una cuenta con ventajas fiscales no añade rendimiento por sí misma — solo deja que una parte mayor del crecimiento se capitalice sin interrupciones. ¿Por qué podría importar eso más cuanto antes empieza alguien?"
  },
  "7": {
    "sections": [
      {
        "heading": "Los Tramos Fiscales Son Capas, No una Tasa Única",
        "body": "Imagina el impuesto sobre la renta como una pila de cubos, cada uno con su propia tasa, y el dinero los llena de abajo hacia arriba. El primer cubo puede gravar la primera porción del ingreso a una tasa baja; una vez que ese cubo se llena, la siguiente porción rebosa a un cubo gravado a una tasa más alta — pero solo esa porción, no todo lo que hay debajo.\n\nPor eso un aumento nunca puede reducir tu sueldo neto, aunque te empuje a un tramo nuevo. Supón que el ingreso de un trabajador crece lo suficiente para rebosar a un cubo superior. Solo la porción nueva y adicional del ingreso — la parte que se desbordó a ese cubo más alto — se grava a la tasa más alta. Cada dólar de los cubos inferiores se sigue gravando exactamente igual que antes.\n\nUn error común y costoso es pensar que un aumento, o un bono, puede dejarte con menos dinero en total por «empujarte a un tramo más alto». No puede — solo puede significar que los dólares marginales (los adicionales) se gravan un poco más, nunca que el ingreso ya ganado se grave retroactivamente a la nueva tasa más alta. Pero los tramos no son lo único ligado al ingreso: algunas ayudas públicas, como la ayuda para el cuidado infantil o Medicaid, bajan bruscamente cuando el ingreso supera un límite, y cerca de ese límite (lo que se llama un precipicio de beneficios) un aumento pequeño puede dejar a un hogar con menos dinero en total aunque su sueldo neto suba."
      },
      {
        "heading": "Sueldo Bruto, Sueldo Neto y A Dónde Va la Diferencia",
        "body": "Mira cualquier recibo de sueldo y destacan dos cifras: el sueldo bruto (todo lo ganado antes de descontar nada) y el sueldo neto (lo que realmente llega a la cuenta bancaria). La diferencia entre ambos suele ser más que solo el impuesto sobre la renta.\n\nEn EE.UU., de un cheque de pago normalmente también se retienen impuestos de nómina aparte — que financian programas como el Seguro Social y Medicare — y, según el estado, un impuesto estatal sobre la renta además del federal. El empleador suele retener todo eso automáticamente antes de que el dinero llegue al trabajador, y por eso la mayoría nunca tiene que entregar una suma grande en la temporada de impuestos: casi todo ya se recaudó cheque a cheque.\n\nEsto conecta directamente con “Cuentas de Jubilación”: una aportación a un 401(k) Traditional sale del sueldo antes de que se retenga el impuesto federal sobre la renta, y por eso reduce el impuesto federal que se descuenta en ese recibo. Los impuestos del Seguro Social y de Medicare se siguen reteniendo sobre ella. Una IRA Traditional se maneja en la declaración de impuestos: cualquier deducción que genere se reclama allí, no en el recibo de sueldo."
      },
      {
        "heading": "Un Reembolso Grande No Es un Regalo — Es un Préstamo Sin Intereses",
        "body": "La retención de cada cheque de pago es solo una estimación del impuesto real del año, basada en las respuestas del Formulario W-4 que se completa al empezar un trabajo — estado civil, número de empleos, otros ingresos. El monto real no se calcula hasta presentar la declaración la primavera siguiente, meses después de que la mayoría de los pagos del año ya se cobraron.\n\nSi la estimación retuvo más de lo que resultó ser el impuesto real, la diferencia vuelve como un reembolso. Es fácil tratarlo como un bono, pero era dinero del trabajador todo el tiempo — entregado por adelantado, retenido sin intereses, y devuelto después al mismo valor. Un reembolso de $3,000 significa que $3,000 quedaron fuera de alcance durante meses, sin poder ir a una cuenta, una deuda o un ahorro en el momento en que realmente se ganaron.\n\nSi la estimación retuvo menos de lo real, el trabajador debe la diferencia al presentar la declaración, y una brecha suficientemente grande puede sumar una multa por pago insuficiente. Ningún resultado cambia cuánto impuesto se debía ese año — la retención solo controla cuándo cambia de manos ese dinero, no el tamaño de la factura.\n\nEl W-4 es la palanca para ajustar la estimación, y es el documento que la mayoría llena una sola vez, el primer día de trabajo, y nunca vuelve a revisar — ni tras un aumento, un segundo empleo, un matrimonio o un nuevo dependiente. Un reembolso o saldo adeudado que varía mucho de un año a otro suele reflejar un W-4 desactualizado, no un impuesto impredecible."
      }
    ],
    "takeaway": "Los tramos fiscales gravan capas de ingreso, no todo el ingreso a una sola tasa. Un aumento nunca puede restar de tu sueldo neto, solo sumar, aunque cerca del límite de ingresos de una ayuda pública, perder esa ayuda puede costar más de lo que suma el aumento.",
    "thinkAbout": "Ahora que entiendes los tramos marginales, piensa en la pregunta Traditional vs Roth de la lección “Cuentas de Jubilación”. Una aportación Traditional normalmente reduce el ingreso gravable, y como esos dólares salen de la porción más alta del ingreso, el impuesto que ahorra se calcula sobre todo a la tasa marginal de hoy. ¿Cambia eso tu forma de pensar la comparación?"
  },
  "8": {
    "sections": [
      {
        "heading": "El Seguro Agrupa el Riesgo Entre Muchas Personas",
        "body": "Imagina un vecindario de mil casas. En un año dado, quizás dos o tres tendrán un incendio grave, pero nadie sabe cuáles de antemano. Si cada propietario tuviera que cubrir por su cuenta el costo total de un incendio, un puñado de familias con mala suerte enfrentaría una pérdida devastadora mientras todos los demás no pagarían nada.\n\nEl seguro cambia esa cuenta. Cada propietario paga una cantidad relativamente pequeña — la prima — a un fondo compartido. El asegurador usa ese fondo para pagar el costo total de las pocas casas que sí tienen un incendio ese año. Nadie sabe de antemano si será de los pocos desafortunados, así que todos cambian un costo pequeño y seguro (la prima) por protección ante uno grande e incierto (reconstruir una casa desde cero).\n\nEsta es la misma idea de fondo en todo tipo de seguro — salud, auto, hogar o inquilino, vida — solo que aplicada a una clase distinta de riesgo: un grupo grande de personas expuestas a la misma categoría de pérdida impredecible, que aportan cantidades pequeñas para que los pocos que de verdad la sufren no queden solos ante ella."
      },
      {
        "heading": "Primas, Deducibles y Límites de Cobertura",
        "body": "Tres cifras dan forma a casi toda póliza de seguro. La prima es el importe recurrente que se paga para mantener la cobertura activa, se presente o no un reclamo alguna vez. El deducible es lo que el asegurado paga de su bolsillo antes de que el asegurador empiece a pagar algo de un reclamo. El límite de cobertura es el máximo que el asegurador pagará, incluso si la pérdida real es mayor.\n\nLas tres interactúan directamente. Una póliza con un deducible más alto generalmente lleva una prima más baja, porque el asegurado acepta absorber él mismo más de las pérdidas pequeñas y frecuentes — el asegurador solo interviene cuando las cosas se ponen más caras. Una póliza con un deducible más bajo generalmente lleva una prima más alta, ya que el asegurador asume más del costo desde el primer dólar.\n\nEse balance — un poco más pagado cada mes frente a un poco más pagado de tu bolsillo si algo sale mal — depende de las finanzas, la tolerancia al riesgo y las circunstancias de cada persona, no de una regla que esta lección pueda dar. El objetivo aquí es entender cómo encajan las piezas, no qué combinación es la correcta para una persona en particular."
      },
      {
        "heading": "Selección Adversa y Riesgo Moral: Por Qué los Aseguradores Preguntan Tanto",
        "body": "La sección 1 explicó que la agrupación de riesgo solo funciona porque nadie sabe de antemano quién será el desafortunado. Dos fuerzas pueden romper esa suposición en silencio, y los aseguradores dedican un esfuerzo real a manejar ambas.\n\nLa primera es la selección adversa: quienes ya saben que tienen mayor riesgo son más propensos a comprar seguro, y a comprar más cobertura, que quienes se saben de bajo riesgo — un fumador tiene más motivos para querer un seguro de vida que un corredor de maratón. Si el asegurador cobrara a todos la misma prima sin importar eso, el fondo se llenaría de forma desproporcionada con las personas con más probabilidad de reclamar, empujando las primas al alza para todos. Por eso las solicitudes de seguros de vida, de auto o de hogar preguntan por el historial médico, el historial de manejo o el estado de la vivienda antes de fijar el precio — clasificar a la gente en grupos de riesgo precisos es una forma de mantener el fondo viable. La otra es que las personas de bajo riesgo también permanezcan en él: por eso muchos países hacen obligatorio el seguro de salud y fijan su prima según los ingresos, no según la salud.\n\nLa segunda es el riesgo moral: una vez cubierta una pérdida, el comportamiento del asegurado puede cambiar de maneras que hacen esa pérdida más probable, ya que ya no asume su costo completo. Los deducibles existen en parte por esto — dejan al asegurado con algo en juego.\n\nAlgunas pérdidas quedan por completo fuera de lo que un seguro puede cubrir: algo que ya ocurrió, el desgaste normal en lugar de un suceso repentino, o un daño enteramente bajo el control del asegurado. Ninguna implica la incertidumbre real de la que depende la agrupación."
      }
    ],
    "takeaway": "El seguro no elimina el riesgo — lo agrupa entre muchas personas para que una pérdida grande y rara se convierta en un costo pequeño y predecible para todos. Prima, deducible y límite de cobertura son las tres palancas de ese balance.",
    "thinkAbout": "La lección “Fondo de Emergencia” trató sobre construir un fondo de emergencia para gastos inesperados. El seguro y un fondo de emergencia resuelven problemas relacionados pero distintos — uno agrupa el riesgo entre muchas personas para pérdidas demasiado grandes para la mayoría de los presupuestos individuales, el otro es dinero que una sola persona aparta para sorpresas más pequeñas y cotidianas. ¿Puedes pensar en una pérdida que cada uno cubriría mejor?"
  },
  "9": {
    "sections": [
      {
        "heading": "Por Qué un Dólar Compra Menos Con el Tiempo",
        "body": "Pregúntale a un abuelo cuánto costaba una entrada de cine o una barra de pan cuando era joven — el número sonará minúsculo. No es que esas cosas se volvieran más valiosas; es el reverso de la definición de inflación (lección “El Ciclo de Deuda a Corto Plazo” (en Cómo funciona la economía)): cuando el gasto y los ingresos de una economía crecen más rápido que los bienes y servicios que realmente se producen, los precios suben. Repetido año tras año, ese ascenso constante significa que el mismo dólar compra cada año un poco menos que antes.\n\nEsto importa más para el dinero que simplemente se queda quieto. Imagina $1,000 en efectivo guardados en un cajón durante veinte años, sin tocarlos nunca. El número impreso en esos billetes no cambia jamás — siguen siendo $1,000. Pero la compra del supermercado, la gasolina y el alquiler que esos $1,000 habrían cubierto el primer día costarían bastante más veinte años después, de modo que ese mismo fajo de billetes cubre hoy menos vida cotidiana que antes.\n\nY no es un defecto exclusivo del efectivo en un cajón — es lo que la inflación le hace al poder adquisitivo en general, ya esté el dinero en un cajón, en una cuenta de ahorros de bajo interés o en cualquier otro sitio que no crezca lo bastante rápido como para seguirle el ritmo."
      },
      {
        "heading": "Rendimiento Real vs Rendimiento Nominal",
        "body": "Una cuenta de ahorros con interés parece proteger contra esto — el saldo crece cada año. Pero ese número es el rendimiento nominal: crecimiento en dólares simples, sin preguntar qué pueden comprar esos dólares.\n\nEl rendimiento real vuelve a restar la inflación: aproximadamente, rendimiento real ≈ rendimiento nominal − tasa de inflación. Si una cuenta crece un porcentaje modesto en un año en que los precios de la economía subieron un porcentaje similar o mayor, el saldo es mayor en dólares pero está prácticamente plano — o incluso encogiendo — en términos de lo que realmente puede comprar. Un saldo mayor en dólares no siempre significa más riqueza real.\n\nPor eso importa tanto lo que la lección “Interés Compuesto” dice sobre la capitalización: para que el crecimiento de una cuenta se traduzca en un poder adquisitivo creciente, y no en números meramente crecientes, la capitalización tiene que superar a la inflación, no solo ser positiva."
      }
    ],
    "takeaway": "Un saldo creciente no es lo mismo que riqueza creciente. Lo que importa es el rendimiento real — crecimiento nominal menos inflación — porque eso es lo que determina si el poder adquisitivo real de tu dinero está subiendo o bajando.",
    "thinkAbout": "La lección “Interés Compuesto” mostró que la capitalización premia el tiempo sobre casi todo lo demás. Ahora añade la inflación: el dinero quieto, incluso con un poco de interés, puede perder poder adquisitivo real cada año que la inflación lo supere. ¿Cambia eso tu forma de pensar sobre ahorrar frente a simplemente no gastar?"
  },
  "10": {
    "sections": [
      {
        "heading": "¿Empleado (W-2) o Contratista Independiente (1099)?",
        "body": "El pasado enero, dos diseñadoras gráficas abrieron su correo. Nadia, en plantilla en una agencia, con horario fijo y un jefe, encontró un único W-2 de su empleador. Priya, que acepta proyectos freelance para un puñado de clientes, fija su propio horario y usa su propio equipo, encontró un 1099 distinto de cada cliente que le había pagado por encima de cierto umbral. Ejercen el mismo oficio — los formularios difieren porque difieren las relaciones laborales.\n\nUn W-2 y un 1099 son ambos formularios fiscales que un trabajador recibe cada enero resumiendo la paga del año anterior — pero cuál de los dos te llega depende de tu relación laboral, no de tu título de puesto. Un W-2 significa que eres empleado: tu empleador dirige cómo, cuándo y dónde se hace el trabajo y — como explicó la lección “Impuestos” — retiene automáticamente el impuesto sobre la renta y los impuestos de nómina de cada cheque. Un 1099 significa que te pagaron como contratista independiente: una empresa o un cliente te pagó por un servicio, pero no se retuvo nada, y no existió ninguna relación de empleo.\n\nEl mismo tipo de trabajo puede aparecer de cualquiera de las dos formas, y por eso el correo de Nadia y el de Priya no se parecen en nada. La distinción no va sobre qué trabajo se hizo — va sobre quién controla cómo se hace, y cambia lo que ocurre con los impuestos."
      },
      {
        "heading": "El Impuesto de Trabajo por Cuenta Propia: Pagando Ambas Mitades",
        "body": "La lección “Impuestos” explicó que la diferencia entre el sueldo bruto y el neto de un cheque incluye impuestos de nómina que financian el Seguro Social y Medicare — y que normalmente un empleador retiene y paga parte de eso automáticamente. Lo que aquella lección no dijo: el empleador no paga ese impuesto de nómina solo. Se divide aproximadamente a la mitad entre empleador y empleado, y la mitad del empleador ni siquiera aparece en el recibo de sueldo del empleado.\n\nUn contratista 1099 no tiene empleador que cubra esa otra mitad — así que un trabajador por cuenta propia debe ambas mitades él mismo, un impuesto de trabajo por cuenta propia combinado que se suma al impuesto sobre la renta ordinario. Como no se retiene nada automáticamente de un pago 1099 como sí ocurre con un cheque W-2, la responsabilidad se traslada por completo al trabajador: apartar dinero de cada pago y — según cuánto se deba — enviar pagos de impuestos estimados al IRS trimestralmente a lo largo del año, en vez de pagarlo todo de golpe la primavera siguiente.\n\nPor eso exactamente se les dice de forma constante a los freelancers, a los trabajadores de la economía gig y a los dueños de pequeños negocios que aparten aproximadamente entre una cuarta parte y un tercio de lo que ganan antes de que llegue siquiera a su cuenta corriente: con un W-2, ese apartado ya ocurrió automáticamente, cheque a cheque."
      }
    ],
    "takeaway": "El mismo trabajo puede llegar como W-2 o 1099, y esa distinción decide si los impuestos se retienen automáticamente o si el trabajador debe apartarlos y pagarlos él mismo — incluido un impuesto de trabajo por cuenta propia que cubre la mitad que normalmente paga el empleador.",
    "thinkAbout": "La lección “Impuestos” mostró que un aumento nunca reduce tu sueldo neto, porque solo la porción que rebosa a un tramo superior se grava a la tasa más alta. Ahora imagina ese mismo aumento llegando como ingreso 1099 — sin nada retenido. ¿Cambia eso cómo evaluarías una oportunidad freelance frente a un salario con el mismo número nominal?"
  },
  "11": {
    "sections": [
      {
        "heading": "El Ratio de Gastos: Una Comisión Que Nunca Te Facturan",
        "body": "Los fondos mutuos y ETFs cobran una comisión anual llamada ratio de gastos, expresada como porcentaje del dinero invertido. A diferencia de una factura de teléfono, nada llega pidiendo ser pagado: el fondo simplemente deduce continuamente una pequeña porción de los activos totales, así que el saldo que ve el inversionista ya tiene la comisión descontada. Esa invisibilidad es justo lo que la hace fácil de ignorar.\n\nLos ratios de gastos varían enormemente. Un fondo que simplemente sigue un índice de mercado suele cobrar 0.03%-0.20% al año. Un fondo con un gestor que elige activamente las inversiones suele cobrar 0.5%-1.5% al año — y la mayoría de los fondos gestionados activamente no superan de forma confiable a un fondo índice comparable después de comisiones, a largo plazo."
      },
      {
        "heading": "Por Qué Una Comisión Pequeña Se Vuelve Grande",
        "body": "La lección “Interés Compuesto” mostró que el dinero crece más rápido cuando el interés compuesto tiene más años para trabajar — y que la misma matemática funciona en tu contra con deudas, donde el interés no pagado también se compone. Una comisión funciona igual: se resta cada año, incluso sobre el crecimiento que la comisión ya se llevó en años anteriores.\n\nCon $10,000 invertidos 30 años a un 7% anual: con una comisión de 0.05%, el saldo llega a unos $75,000. Con una comisión de 1.05% — solo un punto porcentual de diferencia — el saldo llega a apenas unos $57,000. Esa diferencia de un punto, compuesta durante 30 años, se llevó aproximadamente una cuarta parte del saldo total.\n\nEsto no significa que el fondo más barato siempre sea la mejor opción. Pero como la comisión es segura y se compone mientras el dinero esté invertido, mientras que el desempeño futuro no lo es, revisar el ratio de gastos antes de invertir es algo que un inversionista puede saber con certeza de antemano."
      }
    ],
    "takeaway": "Una comisión nunca envía una factura, pero se compone cada año igual que el interés de la lección “Interés Compuesto” — solo que en contra del saldo en vez de a favor, por eso vale la pena revisarla antes de invertir aunque sea menor al 1%.",
    "thinkAbout": "Dos fondos siguen el mismo índice y tienen inversiones casi idénticas, pero uno cobra 0.05% y el otro 0.75% al año. Como la lección “Acciones, Bonos y Diversificación” mostró que la diversificación, no la habilidad para elegir acciones, es lo que ya ofrece un fondo índice, ¿qué justificaría pagar la comisión más alta por las mismas inversiones subyacentes?"
  },
  "12": {
    "sections": [
      {
        "heading": "Alquilar vs. Comprar: Lo Que Cada Camino Realmente Cuesta",
        "body": "El alquiler y el pago de una hipoteca parecen el mismo tipo de gasto: un cheque que se escribe cada mes por la vivienda, pero compran cosas muy distintas. El alquiler compra el derecho a vivir en un lugar durante un período fijo, sin ningún derecho a largo plazo sobre la propiedad; cuando termina el contrato, el inquilino se va sin haber sumado nada a su propio patrimonio. A cambio, el propietario absorbe los costos sorpresa de la propiedad —un calentador de agua roto, un techo nuevo, impuestos a la propiedad en aumento— y el inquilino normalmente puede mudarse con uno o dos meses de aviso.\n\nComprar cambia esa flexibilidad por otra cosa: una parte de cada pago de hipoteca construye capital (equity), es decir, una participación en la vivienda que el comprador conserva o recupera más adelante. Pero comprar también adelanta costos que un inquilino nunca ve. Primero está el pago inicial: en las hipotecas para comprar vivienda en EE. UU. en 2024, fue del 20% o más del precio en casi la mitad, y de menos del 5% en aproximadamente una cuarta parte. Los costos de cierre —comisiones por el préstamo, búsqueda de título, inspección, y más— suelen añadir entre 2% y 5% del precio de compra además del pago inicial, y venderla después normalmente cuesta otro 5%-6% en comisiones de agente: el promedio nacional en EE. UU. lleva años cerca del 5.5%, repartido casi por mitades entre el agente de cada parte. Son tarifas negociables y no fijas, y un acuerdo judicial de 2024 cambió la práctica en EE. UU. de modo que ya no se da por sentado que el vendedor cubra la mitad correspondiente al agente del comprador; la mayoría de los vendedores todavía lo hace, y esa parte apenas ha variado desde entonces.\n\nUn propietario también carga con los mismos costos sorpresa que antes absorbía el arrendador: impuestos a la propiedad, seguro de vivienda (la idea de la lección “Seguros” de cambiar un costo pequeño por protección, ahora obligatorio para quien tiene una hipoteca), y reparaciones. Nada de esto significa que comprar sea un error o que alquilar sea 'tirar el dinero' — significa que las dos opciones combinan costo, riesgo y flexibilidad de manera distinta, y qué combinación conviene depende de cuánto tiempo alguien planea quedarse y qué haría con el dinero de otra manera."
      },
      {
        "heading": "De Qué Está Hecho en Realidad un Pago de Hipoteca",
        "body": "Una hipoteca es un préstamo que usa la propia vivienda como garantía: si los pagos se detienen, el prestamista puede ejecutar la hipoteca y quedarse con la vivienda para recuperar lo adeudado, razón por la cual los prestamistas pueden ofrecer tasas de interés más bajas en una hipoteca que en un préstamo sin garantía como una tarjeta de crédito. Un pago mensual típico agrupa cuatro elementos —capital (reducir el monto prestado), interés (el cargo del prestamista por el préstamo), impuestos a la propiedad y seguro de vivienda— aunque solo los dos primeros forman parte del préstamo en sí.\n\nLa división entre capital e interés cambia a lo largo de la vida del préstamo de una forma que muchos compradores no esperan: los primeros pagos son sobre todo interés, y los últimos son sobre todo capital. No es el interés compuesto de la lección “Interés Compuesto”: su advertencia sobre las deudas habla del interés que no se paga, y cada pago normal de una hipoteca estándar cubre por completo el interés de ese mes. La causa es más simple —el interés se cobra sobre todo el saldo restante, así que cuando el saldo es más grande (justo después de comprar), la porción de interés también lo es. Un préstamo a 30 años cruza el punto medio entre interés y capital en un momento que determina la tasa de interés, no el tamaño del préstamo: con una tasa cercana al 7%, aproximadamente dos tercios de su plazo, alrededor del año 20; con una tasa del 3%, alrededor del año 7.\n\nUn pago inicial menor al 20% del precio de compra suele añadir un costo más: el seguro hipotecario privado (PMI), que protege al prestamista —no al comprador— si el préstamo entra en impago, y que normalmente se cancela automáticamente una vez que se ha acumulado suficiente capital. Un pago inicial más grande reduce el monto del préstamo, el pago mensual, y a menudo evita el PMI por completo, lo cual es parte de por qué el tamaño del pago inicial es una de las cifras más discutidas al comprar una vivienda."
      }
    ],
    "takeaway": "Alquilar y comprar no son una opción 'correcta' y otra 'incorrecta' — intercambian flexibilidad y costos predecibles por capital y riesgo inicial en distintas proporciones, y el propio pago de la hipoteca se divide en capital, interés, impuestos y seguro, con la mayor parte de interés en los primeros años del préstamo.",
    "thinkAbout": "Alguien está comparando un apartamento que se alquila por $1,800/mes con una vivienda donde la hipoteca, los impuestos y el seguro sumarían $1,900/mes — casi lo mismo. Dado que comprar también requiere un pago inicial más 2%-5% en costos de cierre por adelantado, y que vender después cuesta otro 5%-6% en comisiones, ¿qué más importaría antes de concluir que las dos opciones cuestan 'casi lo mismo'?"
  },
  "13": {
    "sections": [
      {
        "heading": "Qué Es (y Qué No Es) una Cuenta de Corretaje",
        "body": "Una cuenta de corretaje es solo un contenedor: un lugar para guardar inversiones, no una inversión en sí misma. Abrir una suele ser gratis y no compromete dinero por sí sola; la cuenta solo empieza a funcionar cuando se deposita dinero y luego se usa para comprar algo dentro de ella, como las acciones, bonos o fondos de la lección “Acciones, Bonos y Diversificación”.\n\nEso es fácil de pasar por alto con el efectivo dentro de la cuenta. El dinero depositado que no se ha usado para comprar nada normalmente se queda ahí sin más — una cuenta de corretaje no es una cuenta de ahorros, así que el efectivo sin invertir suele generar poco o nada por sí solo. Comprar una inversión real es un paso separado y deliberado, no algo automático.\n\nUna cuenta de corretaje sujeta a impuestos también es distinta de las cuentas 401(k) e IRA de la lección “Cuentas de Jubilación”. No tiene límite de aportación ni penalización por retirar dinero antes, pero las ganancias se gravan al realizarse — cuando se vende una inversión con ganancia — en vez del trato diferido o libre de impuestos de una cuenta de jubilación. Muchas personas terminan usando ambos tipos de cuenta para metas distintas: las cuentas con ventajas fiscales para la jubilación, y una cuenta de corretaje sujeta a impuestos para el dinero que podría necesitarse antes."
      },
      {
        "heading": "Colocar una Orden: Mercado vs. Límite",
        "body": "Una vez que hay dinero en la cuenta, comprar o vender algo requiere colocar una orden, y los dos tipos más comunes funcionan de forma distinta. Una orden de mercado dice 'compra (o vende) ahora mismo, al mejor precio disponible' — se ejecuta casi de inmediato, pero el precio exacto no está garantizado, sobre todo si el precio se mueve rápido. Una orden límite en cambio fija un precio específico: 'solo compra a este precio o menos' (o 'solo vende a este precio o más') — el precio está garantizado si la orden se ejecuta, pero no hay garantía de que se ejecute, ya que el mercado podría no llegar nunca a ese precio.\n\nLa mayoría de las plataformas también permiten comprar acciones fraccionarias — una parte de una acción, como $50 de una acción que cotiza a $500 — en vez de exigir la compra de acciones completas, lo que facilita construir la diversificación de la lección “Acciones, Bonos y Diversificación” con menos dinero. Y una operación completada no termina al instante: las acciones suelen 'liquidarse' —cambiar oficialmente de propietario— un día hábil después de la operación, un detalle que sobre todo importa si quieres usar enseguida el dinero de una venta para comprar otra cosa."
      },
      {
        "heading": "Si las Operaciones Son Gratis, ¿Quién Paga Esto?",
        "body": "La mayoría de las plataformas de corretaje ya no cobran comisión por comprar o vender acciones — un cambio real respecto a hace unas décadas, cuando una sola operación podía costar entre $10 y $30 sin importar el monto. Pero una empresa sigue necesitando ingresos para operar, así que \"gratis\" describe lo que el inversor paga directamente, no lo que gana la plataforma.\n\nTres fuentes de ingresos cubren la mayor parte de esa diferencia. Interés: el efectivo que espera dentro de la cuenta para ser invertido — el mismo efectivo sin invertir descrito arriba — se agrupa entre todos los clientes, y la propia plataforma puede prestarlo o invertirlo de un día para otro, quedándose con el interés, la misma razón por la que un banco puede ofrecer cuentas corrientes \"gratis\". Pago por flujo de órdenes (payment for order flow): en lugar de enviar cada orden directamente a una bolsa pública, muchas plataformas la dirigen a un creador de mercado (market maker) — una firma que ejecuta la orden directamente y paga a la plataforma una pequeña comisión por ese derecho. El diferencial de compra-venta (bid-ask spread): en cualquier momento, una acción tiene un precio de compra ligeramente más alto (ask) que de venta (bid) — a menudo apenas uno o dos centavos — y el creador de mercado que ejecuta la orden se queda con esa diferencia.\n\nNada de esto es oculto ni ilegal — las plataformas deben divulgar públicamente sus prácticas de enrutamiento de órdenes, y la regulación exige que las operaciones obtengan \"la mejor ejecución\", un precio razonable según las condiciones del mercado en ese momento. Pero \"sin comisión\" no es lo mismo que \"la plataforma no tiene ningún interés en esta operación\". Vale la pena recordarlo la próxima vez que algo se anuncie como gratis: al menos una vez, conviene preguntarse de dónde viene realmente el ingreso."
      }
    ],
    "takeaway": "Una cuenta de corretaje es un contenedor, no una inversión — abrirla es gratis, pero el dinero dentro solo crece una vez que se usa para comprar algo. Las órdenes de mercado cambian certeza de ejecución por incertidumbre de precio; las órdenes límite hacen lo contrario.",
    "thinkAbout": "Alguien coloca una orden límite para comprar una acción 5% por debajo de su precio actual, esperando un mejor trato, pero el precio nunca baja tanto y la orden nunca se ejecuta. Comparado con usar una orden de mercado, ¿qué sacrificó — y qué riesgo evitó?"
  },
  "14": {
    "sections": [
      {
        "heading": "Un Testamento No Es Solo para los Ricos",
        "body": "Un testamento es un documento legal que indica quién recibe las pertenencias, el dinero y las propiedades de una persona después de morir, y — para quienes tienen hijos menores — quién los criaría. Es fácil suponer que un testamento solo importa para alguien con un patrimonio grande, pero su función real es más simple: deja que los deseos de la persona, no una fórmula predeterminada, decidan qué pasa con lo que deja atrás.\n\nSin testamento, la ley estatal decide en su lugar, mediante un proceso llamado sucesión intestada — una fórmula fija que se aplica de la misma manera sin importar lo que la persona realmente hubiera querido.\n\nUn testamento no tiene que ser complicado para cumplir su función principal, y crear uno suele ser mucho menos complejo de lo que la mayoría supone — pero los detalles varían según el lugar y la situación."
      },
      {
        "heading": "Las Designaciones de Beneficiario Pueden Anular un Testamento",
        "body": "Aquí hay un detalle que sorprende a muchos: un testamento no lo controla todo. Ciertas cuentas — incluidas las cuentas 401(k) e IRA de la lección “Cuentas de Jubilación” y las pólizas de seguro de vida de la lección “Seguros” — pasan directamente a quien esté designado como beneficiario, sin importar lo que diga el testamento. La designación de beneficiario de la cuenta siempre gana, incluso sobre un testamento más reciente que diga algo distinto.\n\nEsto crea un error común y evitable: alguien actualiza su testamento tras un cambio importante — un divorcio, un nuevo hijo, un nuevo matrimonio — pero olvida que un 401(k) o seguro de vida antiguo todavía tiene como beneficiario a un ex-cónyuge.\n\nLa conclusión práctica no es una instrucción específica sobre quién debería ser el beneficiario de nadie — eso depende de las relaciones y circunstancias de cada persona — sino el mecanismo en sí: los formularios de beneficiario son una decisión separada y activa de un testamento, y no se actualizan solos."
      }
    ],
    "takeaway": "Un testamento dirige cómo se distribuyen las pertenencias y el dinero de alguien y quién cría a sus hijos — sin uno, una fórmula legal fija decide en su lugar. Pero las cuentas de jubilación y seguro pasan por alto el testamento por completo: quien esté designado en el formulario de beneficiario de la cuenta la recibe, así que una designación desactualizada puede anular incluso un testamento recién escrito.",
    "thinkAbout": "Alguien se divorcia, reescribe su testamento para dejarle todo a su nuevo cónyuge, pero nunca actualiza la designación de beneficiario del 401(k) que abrió años antes (lección “Cuentas de Jubilación”) — todavía figura su ex-cónyuge. Según esta lección, ¿quién recibe realmente ese 401(k) cuando esa persona muere?"
  },
  "15": {
    "sections": [
      {
        "heading": "El Informe Es el Registro; el Puntaje Es un Número Calculado a Partir de Él",
        "body": "Un informe de crédito es un registro detallado del historial crediticio de una persona: qué tarjetas de crédito y préstamos ha abierto, cuánto debe, si los pagos llegaron a tiempo o tarde, cuánto tiempo lleva abierta cada cuenta, qué prestamistas han consultado recientemente el informe tras una solicitud de crédito (una \"consulta dura\"; que una persona revise su propio informe es una \"consulta blanda\" y no baja su puntaje), y cualquier registro público como bancarrotas. Lo compila una agencia de crédito — las tres principales en EE. UU. son Equifax, Experian y TransUnion — a partir de información que prestamistas, arrendadores y otros acreedores eligen reportar.\n\nUn puntaje de crédito es algo completamente distinto: un número de tres dígitos, generalmente entre 300 y 850, calculado a partir de lo que contiene un informe usando un modelo de puntuación como FICO o VantageScore. El puntaje no se guarda en el informe — se genera a partir de su contenido cuando se solicita, de la misma forma que un promedio académico se calcula a partir de una boleta de calificaciones en lugar de estar escrito directamente en ella.\n\nComo hay tres agencias y varios modelos de puntuación, una sola persona no tiene un puntaje de crédito — tiene varios, y pueden diferir. No todos los prestamistas reportan a las tres agencias, así que el archivo de Equifax sobre una persona puede no incluir una cuenta que sí aparece en el de Experian, y FICO y VantageScore pueden convertir el mismo informe en números ligeramente distintos. Ver dos puntajes diferentes en dos aplicaciones distintas no es un error — puede simplemente significar que las apps consultaron agencias diferentes o usaron modelos diferentes."
      },
      {
        "heading": "Porque un Informe Es un Registro, Puede Contener Errores — y Puede Corregirse",
        "body": "Como un informe de crédito lo compila un tercero a partir de datos de otras empresas, puede estar equivocado de las maneras habituales en que cualquier registro compilado de varias fuentes puede estarlo: un pago que fue puntual se registra como tardío, una cuenta que se cerró sigue apareciendo como abierta, o — más grave aún — información de otra persona con un nombre parecido o un caso de robo de identidad termina en el archivo equivocado. Cualquiera de estos errores puede bajar el puntaje calculado a partir de ese informe, por una razón que no tiene nada que ver con el comportamiento real de esa persona como prestataria.\n\nLa ley federal de EE. UU. da a todos el derecho a una copia gratuita de su informe de crédito de cada una de las tres agencias, disponible en AnnualCreditReport.com, y otorga a los consumidores el derecho a disputar formalmente información inexacta directamente ante la agencia que la reporta. Esto es una acción distinta a mejorar un puntaje: disputar un informe corrige información errónea; no convierte información exacta en algo más favorable.\n\nEsta distinción importa porque ambas cosas suelen confundirse. Si un informe muestra correctamente un historial de pagos tardíos o un saldo alto en relación con el crédito disponible, disputarlo no eliminará esa información — un puntaje calculado a partir de información exacta solo cambia cuando cambia el comportamiento subyacente, con el tiempo. Revisar un informe en busca de errores y mejorar los hábitos que refleja con exactitud son dos acciones distintas, y ambas valen la pena."
      }
    ],
    "takeaway": "Un informe de crédito es un registro detallado del historial crediticio de alguien, mantenido por separado por tres agencias distintas (Equifax, Experian, TransUnion). Un puntaje de crédito es un número de tres dígitos calculado a partir de ese informe mediante un modelo de puntuación (como FICO o VantageScore) — como hay tres agencias y varios modelos, una persona tiene varios puntajes, no uno. Como un informe se compila con datos de otras empresas, puede contener errores; la ley de EE. UU. da a todos el derecho a una copia gratuita de cada agencia y el derecho a disputar inexactitudes, pero disputar solo corrige información errónea — no cambia lo que se reporta con exactitud.",
    "thinkAbout": "Alguien revisa su puntaje de crédito en la app de su banco y ve 705, y luego revisa una app gratuita distinta el mismo día y ve 680. Según esta lección, ¿cuál es la explicación más probable — y alguno de los dos números tiene que estar necesariamente equivocado?"
  },
};
