// Quiz questions, aligned with lesson order.
//
// NOTE ON ANSWER POSITIONS: the correct option is deliberately spread across
// indices (roughly 3/3/4/3 over 0/1/2/3) so the quiz cannot be beaten by
// always tapping the same position. Before this was fixed, 12 of 13 answers
// were index 0 — tap-the-first scored 92%. `npm test` warns if any single
// index ever holds more than half the answers again. When adding a question,
// pick a position that keeps the spread even; when editing options, move the
// whole option string and update `answer` to match — never leave `answer`
// pointing at a position by habit.
export const quizData = [
  { q: { en: "What drives the economy?", es: "¿Qué impulsa la economía?", ko: "경제를 움직이는 것은?", zh: "什么驱动经济？", ja: "経済を動かすものは？" },
    opts: { en: ["Only government spending", "Gold reserves", "Total spending (money + credit)", "Stock prices"], es: ["Solo gasto del gobierno", "Reservas de oro", "Gasto total (dinero + crédito)", "Precios de acciones"], ko: ["정부 지출만", "금 보유량", "총 지출 (돈 + 신용)", "주가"], zh: ["仅政府支出", "黄金储备", "总支出（货币+信贷）", "股票价格"], ja: ["政府支出のみ", "金準備", "総支出（お金+信用）", "株価"] },
    answer: 2, explain: { en: "Total spending drives the economy. Spending = money + credit. Every dollar spent becomes someone else's income.", es: "El gasto total impulsa la economía.", ko: "총 지출이 경제를 움직입니다.", zh: "总支出驱动经济。", ja: "総支出が経済を動かします。" } },
  { q: { en: "What is the most important part of the economy?", es: "¿Cuál es la parte más importante?", ko: "경제에서 가장 중요한 부분은?", zh: "经济中最重要的部分是什么？", ja: "経済で最も重要な部分は？" },
    opts: { en: ["Credit", "Gold", "Government", "Technology"], es: ["Crédito", "Oro", "Gobierno", "Tecnología"], ko: ["신용", "금", "정부", "기술"], zh: ["信贷", "黄金", "政府", "技术"], ja: ["信用", "金", "政府", "技術"] },
    answer: 0, explain: { en: "Credit is the most important and most volatile part of the economy. Total credit outstanding in the US is many times larger than the base money supply.", es: "El crédito es la parte más importante y volátil.", ko: "신용은 경제에서 가장 중요하고 변동성이 큰 부분입니다.", zh: "信贷是经济中最重要、最不稳定的部分。", ja: "信用は経済で最も重要かつ最も変動が大きい部分。" } },
  { q: { en: "How long is the short-term debt cycle?", es: "¿Cuánto dura el ciclo corto?", ko: "단기 부채 순환의 기간은?", zh: "短期债务周期多长？", ja: "短期債務サイクルの期間は？" },
    opts: { en: ["1-2 years", "20-30 years", "75-100 years", "5-8 years"], es: ["1-2 años", "20-30 años", "75-100 años", "5-8 años"], ko: ["1-2년", "20-30년", "75-100년", "5-8년"], zh: ["1-2年", "20-30年", "75-100年", "5-8年"], ja: ["1-2年", "20-30年", "75-100年", "5-8年"] },
    answer: 3, explain: { en: "The short-term debt cycle lasts 5-8 years. It's the business cycle controlled primarily by the central bank through interest rates.", es: "El ciclo corto dura 5-8 años.", ko: "단기 부채 순환은 5-8년입니다.", zh: "短期债务周期持续5-8年。", ja: "短期債務サイクルは5-8年。" } },
  { q: { en: "What causes inflation?", es: "¿Qué causa la inflación?", ko: "인플레이션의 원인은?", zh: "什么导致通胀？", ja: "インフレの原因は？" },
    opts: { en: ["Too little government spending", "Spending growing faster than production", "Low interest rates alone", "Stock market crashes"], es: ["Poco gasto del gobierno", "Gasto creciendo más rápido que producción", "Tasas bajas solas", "Caídas bursátiles"], ko: ["정부 지출 부족", "지출이 생산보다 빠르게 증가", "낮은 금리만으로", "주식시장 폭락"], zh: ["政府支出太少", "支出增长快于生产", "仅低利率", "股市崩盘"], ja: ["政府支出不足", "支出が生産より速く増加", "低金利だけ", "株式市場暴落"] },
    answer: 1, explain: { en: "When spending and incomes grow faster than the production of goods, prices rise. That's inflation.", es: "Cuando el gasto crece más rápido que la producción, los precios suben.", ko: "지출과 소득이 생산보다 빠르게 증가하면 가격이 오릅니다.", zh: "当支出增长快于商品生产时价格上涨。", ja: "支出が生産より速く増えると物価が上がる。" } },
  { q: { en: "What happens during deleveraging that's different from recession?", es: "¿Qué pasa en un desapalancamiento diferente de recesión?", ko: "디레버리징이 경기침체와 다른 점은?", zh: "去杠杆与衰退有什么不同？", ja: "デレバレッジングが景気後退と違う点は？" },
    opts: { en: ["Stock market goes up", "Government stops spending", "Banks have too much money", "Interest rates are already at 0% — can't cut more"], es: ["La bolsa sube", "El gobierno deja de gastar", "Bancos tienen demasiado", "Tasas ya en 0% — no se pueden bajar más"], ko: ["주식시장 상승", "정부 지출 중단", "은행에 돈이 너무 많음", "금리가 이미 0% — 더 인하할 수 없음"], zh: ["股市上涨", "政府停止支出", "银行钱太多", "利率已经是0%——无法再降"], ja: ["株式市場上昇", "政府が支出停止", "銀行の資金過多", "金利がすでに0% — これ以上下げられない"] },
    answer: 3, explain: { en: "In a deleveraging, rates are already at 0%, so the Fed's normal tool (cutting rates) doesn't work. That's why QE and the other tools are needed.", es: "En un desapalancamiento, las tasas ya están en 0%.", ko: "디레버리징에서는 금리가 이미 0%이므로 일반적인 금리 인하가 작동하지 않습니다.", zh: "去杠杆时利率已是0%，普通降息无效。", ja: "デレバレッジでは金利がすでに0%で通常の利下げが機能しない。" } },
  { q: { en: "An inverted yield curve predicts:", es: "Una curva invertida predice:", ko: "수익률 곡선 역전은 무엇을 예측하나요?", zh: "收益率曲线倒挂预示着：", ja: "逆イールドカーブが予測するのは：" },
    opts: { en: ["Immediate stock rally", "Low inflation", "Recession within 12-18 months", "Strong GDP growth"], es: ["Alza inmediata", "Inflación baja", "Recesión en 12-18 meses", "PIB fuerte"], ko: ["즉각적 주가 상승", "낮은 인플레이션", "12-18개월 내 경기침체", "강한 GDP 성장"], zh: ["股市立即上涨", "低通胀", "12-18个月内衰退", "强GDP增长"], ja: ["即座の株価上昇", "低インフレ", "12-18ヶ月以内の景気後退", "強いGDP成長"] },
    answer: 2, explain: { en: "Inverted yield curves have preceded every US recession since 1955 — a strong track record, though not every inversion has been followed by a recession, so it isn't a perfect predictor. When short rates exceed long rates, it signals economic weakness ahead.", es: "Las curvas invertidas han precedido a cada recesión de EE.UU. desde 1955, aunque no toda inversión termina en recesión.", ko: "역전된 수익률 곡선은 1955년 이후 모든 미국 경기침체에 선행했지만, 모든 역전이 경기침체로 이어진 것은 아닙니다.", zh: "倒挂的收益率曲线在1955年以来的每一次美国衰退之前都出现过，但并非每次倒挂后都会发生衰退。", ja: "逆イールドは1955年以来、全ての米国景気後退に先行しましたが、逆イールドの後に必ず景気後退が起きるとは限りません。" } },
  { q: { en: "What is QE (Quantitative Easing)?", es: "¿Qué es QE?", ko: "양적완화(QE)란?", zh: "什么是QE？", ja: "QEとは？" },
    opts: { en: ["Central bank buys bonds to inject money when rates are at 0%", "Government raises taxes", "Banks stop lending", "Prices frozen by law"], es: ["Banco central compra bonos cuando tasas están en 0%", "Gobierno sube impuestos", "Bancos dejan de prestar", "Precios congelados"], ko: ["금리가 0%일 때 중앙은행이 채권 매입으로 자금 공급", "정부 세금 인상", "은행 대출 중단", "법으로 물가 동결"], zh: ["利率为0%时央行买债券注入资金", "政府加税", "银行停贷", "法律冻结价格"], ja: ["金利0%時に中央銀行が債券購入で資金注入", "政府が増税", "銀行が融資停止", "法律で物価凍結"] },
    answer: 0, explain: { en: "QE is the Fed's emergency tool. When rates are at 0%, it prints money to buy bonds, injecting liquidity into the system.", es: "QE es la herramienta de emergencia del Fed.", ko: "QE는 연준의 비상 도구입니다.", zh: "QE是美联储的紧急工具。", ja: "QEはFRBの緊急ツール。" } },
  { q: { en: "The first rule of thumb for managing debt is:", es: "La primera regla general para manejar la deuda es:", ko: "부채 관리의 첫 번째 경험 법칙은:", zh: "管理债务的第一条经验法则是：", ja: "債務管理における最初の経験則は：" },
    opts: { en: ["Always buy stocks", "Never borrow money", "Save 50% of income", "Don't have debt rise faster than income"], es: ["Siempre comprar acciones", "Nunca pedir prestado", "Ahorrar 50%", "No dejes que la deuda crezca más rápido que los ingresos"], ko: ["항상 주식을 사라", "절대 빌리지 마라", "소득의 50%를 저축하라", "부채가 소득보다 빠르게 증가하지 않게 하라"], zh: ["总是买股票", "永不借钱", "存收入的50%", "不要让债务增长快于收入"], ja: ["常に株を買う", "決して借金しない", "収入の50%を貯蓄", "債務が所得より速く増えないようにする"] },
    answer: 3, explain: { en: "If debt rises faster than income, your debt burdens will eventually crush you. This applies to individuals AND nations.", es: "Si la deuda crece más rápido que los ingresos, te aplastará.", ko: "부채가 소득보다 빠르게 증가하면 결국 부채 부담에 짓눌립니다.", zh: "如果债务增长快于收入，债务负担最终会压垮你。", ja: "債務が所得より速く増えると、債務負担に押しつぶされる。" } },
  { q: { en: "What matters most for economic growth in the long run?", es: "¿Qué es lo más importante para el crecimiento económico a largo plazo?", ko: "장기적으로 경제 성장에 가장 중요한 것은?", zh: "从长期来看，什么对经济增长最重要？", ja: "長期的に経済成長にとって最も重要なものは？" },
    opts: { en: ["Credit expansion", "Productivity growth", "Government stimulus", "Stock market gains"], es: ["Expansión del crédito", "Crecimiento de la productividad", "Estímulo gubernamental", "Ganancias del mercado bursátil"], ko: ["신용 확장", "생산성 성장", "정부 부양책", "주식시장 상승"], zh: ["信贷扩张", "生产力增长", "政府刺激", "股市收益"], ja: ["信用拡大", "生産性成長", "政府の景気刺激策", "株式市場の上昇"] },
    answer: 1, explain: { en: "Productivity growth is what raises living standards over the long run. Credit matters most in the short run and creates the cycles — but it can't create real, lasting growth on its own.", es: "El crecimiento de la productividad es lo que eleva el nivel de vida a largo plazo. El crédito importa más a corto plazo y crea los ciclos, pero no puede generar crecimiento real por sí solo.", ko: "생산성 성장이 장기적으로 생활 수준을 높입니다. 신용은 단기적으로 가장 중요하며 순환을 만들지만, 그 자체로는 실질적이고 지속적인 성장을 만들 수 없습니다.", zh: "生产力增长才是长期提升生活水平的因素。信贷在短期最重要，会制造周期——但它自身无法创造真实、持久的增长。", ja: "生産性成長こそが長期的に生活水準を高めるもの。信用は短期的に最も重要でサイクルを生みますが、それ自体では本当の持続的成長は生み出せません。" } },
  { q: { en: "Which of these is NOT one of the 4 tools for reducing a debt burden?", es: "¿Cuál de estas NO es una de las 4 herramientas para reducir la carga de deuda?", ko: "다음 중 부채 부담을 줄이는 4가지 도구가 아닌 것은?", zh: "以下哪一项不是减轻债务负担的4种工具之一？", ja: "次のうち、債務負担を軽減する4つの手段に含まれないものは？" },
    opts: { en: ["Austerity (cutting spending)", "Debt restructuring or default", "Raising interest rates further", "Printing money (QE)"], es: ["Austeridad (recortar gasto)", "Reestructuración o impago de deuda", "Subir aún más las tasas de interés", "Imprimir dinero (QE)"], ko: ["긴축 (지출 삭감)", "부채 구조조정 또는 채무불이행", "금리를 더 인상하는 것", "화폐 발행 (QE)"], zh: ["紧缩（削减支出）", "债务重组或违约", "进一步加息", "印钞（QE）"], ja: ["緊縮（支出削減）", "債務再編またはデフォルト", "さらなる利上げ", "紙幣印刷（QE）"] },
    answer: 2, explain: { en: "The 4 tools are austerity, debt restructuring/default, wealth redistribution (taxes), and printing money. Raising rates further isn't one of them — in a deleveraging, rates are usually already near 0%.", es: "Las 4 herramientas son austeridad, reestructuración/impago, redistribución de riqueza e impresión de dinero. Subir más las tasas no es una de ellas.", ko: "4가지 도구는 긴축, 부채 구조조정/채무불이행, 부의 재분배(증세), 화폐 발행입니다. 금리를 더 올리는 것은 포함되지 않습니다.", zh: "这4种工具是紧缩、债务重组/违约、财富再分配（增税）和印钞。进一步加息不在其中。", ja: "4つの手段は緊縮、債務再編/デフォルト、富の再分配（増税）、紙幣印刷です。さらなる利上げは含まれません。" } },
  { q: { en: "What is the Fed Funds Rate?", es: "¿Qué es la Tasa de Fondos Federales?", ko: "연방기금금리(Fed Funds Rate)란 무엇인가요?", zh: "什么是联邦基金利率？", ja: "FF金利（フェデラルファンド金利）とは何ですか？" },
    opts: { en: ["The key rate that influences nearly all other interest rates", "A tax rate on capital gains", "The interest rate on 30-year Treasury bonds only", "A rate set directly by Congress"], es: ["La tasa clave que influye en casi todas las demás tasas de interés", "Una tasa de impuesto sobre ganancias de capital", "La tasa de interés solo de los bonos del Tesoro a 30 años", "Una tasa fijada directamente por el Congreso"], ko: ["거의 모든 다른 금리에 영향을 미치는 핵심 금리", "자본이득에 대한 세율", "30년 국채에만 적용되는 금리", "의회가 직접 정하는 금리"], zh: ["影响几乎所有其他利率的关键利率", "资本利得税率", "仅适用于30年期国债的利率", "由国会直接设定的利率"], ja: ["ほぼ全ての他の金利に影響を与える基準金利", "キャピタルゲインへの税率", "30年国債にのみ適用される金利", "議会が直接定める金利"] },
    answer: 0, explain: { en: "The Fed Funds Rate is the rate banks charge each other overnight, set by the Federal Reserve. It's the master signal that ripples out to mortgages, savings accounts, and credit cards.", es: "Es la tasa que los bancos se cobran entre sí de un día para otro, fijada por la Reserva Federal.", ko: "연방기금금리는 연방준비제도가 정하는, 은행 간 익일 대출 금리입니다.", zh: "联邦基金利率是银行间隔夜拆借利率，由美联储设定。", ja: "FF金利は連邦準備制度が設定する銀行間のオーバーナイト金利。" } },
  { q: { en: "During the 'Trough' phase of the economic cycle, historically:", es: "Durante la fase de 'Valle' del ciclo económico, históricamente:", ko: "경제 순환의 '저점' 국면에서 역사적으로:", zh: "在经济周期的'低谷'阶段，历史上：", ja: "経済サイクルの「底」局面では、歴史的に：" },
    opts: { en: ["Interest rates are typically at their highest point", "Pessimism is at its worst, but it has often been a strong time to find investment opportunities", "Inflation is usually at its peak", "Stocks have historically continued falling for years afterward"], es: ["Las tasas de interés suelen estar en su punto más alto", "El pesimismo está en su peor momento, pero a menudo ha sido un buen momento para encontrar oportunidades", "La inflación suele estar en su punto máximo", "Las acciones históricamente han seguido cayendo durante años"], ko: ["금리가 보통 최고점에 있습니다", "비관론이 최악이지만, 종종 투자 기회를 찾기 좋은 시기였습니다", "인플레이션이 보통 정점에 있습니다", "주식은 역사적으로 이후 몇 년간 계속 하락했습니다"], zh: ["利率通常处于最高点", "悲观情绪最严重，但这往往是寻找投资机会的好时机", "通胀通常处于顶峰", "股票历史上此后会继续下跌数年"], ja: ["金利が通常最も高い", "悲観が最悪の状態だが、しばしば投資機会を見つけるのに適した時期だった", "インフレが通常ピークにある", "株価は歴史的にその後何年も下落し続けた"] },
    answer: 1, explain: { en: "At the trough, sentiment is at its most negative — but historically, the year following a market bottom has shown some of the strongest average returns, since expansion begins again from there. This is a historical pattern, not a guarantee for any specific future trough.", es: "En el valle, el sentimiento es el más negativo, pero históricamente el año siguiente ha mostrado retornos fuertes. Esto es un patrón histórico, no una garantía.", ko: "저점에서는 심리가 가장 부정적이지만, 역사적으로 시장 바닥 이후 1년은 평균적으로 가장 강한 수익률을 보였습니다. 이는 역사적 패턴이며 보장이 아닙니다.", zh: "在低谷时情绪最负面，但历史上市场触底后一年往往显示最强的平均回报。这是历史规律，不是保证。", ja: "底では心理が最も悲観的になりますが、歴史的に見ると底打ち後の1年は平均リターンが最も強い時期の一つでした。これは歴史的パターンであり保証ではありません。" } },
  { q: { en: "Which economic indicator is often called the 'Fear Gauge'?", es: "¿Qué indicador económico se conoce a menudo como el 'Índice del Miedo'?", ko: "'공포지수'라고 자주 불리는 경제 지표는?", zh: "哪个经济指标常被称为'恐慌指数'？", ja: "「恐怖指数」としばしば呼ばれる経済指標は？" },
    opts: { en: ["GDP", "CPI", "VIX (Volatility Index)", "PMI"], es: ["PIB", "IPC", "VIX (Índice de Volatilidad)", "PMI"], ko: ["GDP", "CPI", "VIX (변동성지수)", "PMI"], zh: ["GDP", "CPI", "VIX（波动率指数）", "PMI"], ja: ["GDP", "CPI", "VIX（ボラティリティ指数）", "PMI"] },
    answer: 2, explain: { en: "The VIX measures expected market volatility. Below 15 signals calm markets; above 40 signals extreme panic. Contrarian investors watch for spikes as potential buying opportunities.", es: "El VIX mide la volatilidad esperada. Por debajo de 15 señala calma; por encima de 40, pánico extremo.", ko: "VIX는 시장의 예상 변동성을 측정합니다. 15 미만은 안정, 40 이상은 극단적 공포를 나타냅니다.", zh: "VIX衡量市场预期波动率。低于15表示平静，高于40表示极度恐慌。", ja: "VIXは市場の予想変動率を測定。15未満は落ち着き、40以上は極度のパニックを示す。" } },
];
